### ISSUE TITLE
Improve the Documentation of the project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#1]

**Comment by goyalmuskan** [comment]
May I work on this issue? @smaranjitghose

**Comment by goyalmuskan** [comment]
The current readme is to be enhanced in this issue? @smaranjitghose

**Comment by smaranjitghose** [comment]
Yes..specifically for the website.

**Comment by shreyakapoor08** [comment]
can i take up this?

**Comment by suchi12j** [comment]
Can I work on this please?

**Comment by smaranjitghose** [comment]
@suchi12j  would you like to improve the codebase with the task 2 I listed above?...
Meanwhile after @shreyakapoor08 gives a PR or two for the READMe..you can improvise further if required

**Comment by suchi12j** [comment]
Yes I will work. But where is task2 above? @smaranjitghose

**Comment by smaranjitghose** [comment]
@suchi12j  please check once now..Its updated

**Comment by shreyakapoor08** [comment]
> @suchi12j would you like to improve the codebase with the task 2 I listed above?...
> Meanwhile after @shreyakapoor08 gives a PR or two for the READMe..you can improvise further if required

i wi raise PR by today evening

**Comment by shreyakapoor08** [comment]
@smaranjitghose PR raised. Kindly check and let me know in case any correction is required.

**Comment by Mansi145** [comment]
hey @smaranjitghose, is this issue open for working? I'd like to work on this.

**Comment by smaranjitghose** [comment]
Try to make it a bit interactive like [this](https://github.com/smaranjitghose/AutoPromPicker)

**Comment by Kuljeet-123** [comment]
@smaranjitghose Can I work on this issue ??

**Comment by smaranjitghose** [comment]
Collaborate with Mansi on this then

**Comment by smaranjitghose** [comment]
@Kuljeet-123 @Mansi145 you are being assigned this for the next 3 days. Post that it shall be reassigned

**Comment by Kuljeet-123** [comment]
@smaranjitghose I will raise the PR by today evening.

**Comment by Kuljeet-123** [comment]
@smaranjitghose Please review my PR and let me know if some correction is needed.

**Comment by rajraman786** [comment]
I want to work on this.

**Comment by anushbhatia** [comment]
Can someone add this
1. git stash  -> save your uncommited stuff, if you need
2. git remote add upstream https://github.com/ururl
3. git fetch upstream 
4. git checkout branch_name  Choose to the branch that you are working
5. git rebase upstream/master  Start the rebase, probably you will need to solve some conflicts, you can always ask here.
6. git stash pop  -> recover your uncommited stuff
7. git push --force  -> sync your branch with remote, *the --force is very important for the first time after rebase, don't forget it.

**Comment by Kuljeet-123** [comment]
> Can someone add this
> 
> 1. git stash  -> save your uncommited stuff, if you need
> 2. git remote add upstream https://github.com/ururl
> 3. git fetch upstream
> 4. git checkout branch_name  Choose to the branch that you are working
> 5. git rebase upstream/master  Start the rebase, probably you will need to solve some conflicts, you can always ask here.
> 6. git stash pop  -> recover your uncommited stuff
> 7. git push --force  -> sync your branch with remote, *the --force is very important for the first time after rebase, don't forget it.

@anushbhatia can I work on this??

**Comment by shreyakapoor08** [comment]
> Can someone add this
> 
> 1. git stash  -> save your uncommited stuff, if you need
> 2. git remote add upstream https://github.com/ururl
> 3. git fetch upstream
> 4. git checkout branch_name  Choose to the branch that you are working
> 5. git rebase upstream/master  Start the rebase, probably you will need to solve some conflicts, you can always ask here.
> 6. git stash pop  -> recover your uncommited stuff
> 7. git push --force  -> sync your branch with remote, *the --force is very important for the first time after rebase, don't forget it.

Yes, Can I do it @anushbhatia

**Comment by Mansi145** [comment]
> Can someone add this
> 
> 1. git stash  -> save your uncommited stuff, if you need
> 2. git remote add upstream https://github.com/ururl
> 3. git fetch upstream
> 4. git checkout branch_name  Choose to the branch that you are working
> 5. git rebase upstream/master  Start the rebase, probably you will need to solve some conflicts, you can always ask here.
> 6. git stash pop  -> recover your uncommited stuff
> 7. git push --force  -> sync your branch with remote, *the --force is very important for the first time after rebase, don't forget it.

I am already assigned to this issue. Can I work on this? I'll make the PR by tonight.

**Comment by smaranjitghose** [comment]
@rajraman786 @shreyakapoor08 Would you be interested in Task 2 mentioned above?
For a quick synopsis, what we wish to achieve here:
- for each of the pages, give detailed comments of what each section of the code is for
- repeat the same for CSS files
- Maintain a Guide.MD file at the root level of the master branch where you have sections (use #) for each page (attach snapshots) and within those specify which part of the code in what file has to be changed (say for the GirlScript Chennai parallax to be made as DSC) for revamping it as some other GirlScipt Chapter's requirement. 
- To make it more user-friendly again mention the specific line in markdown format like:

#### Title of the page

__change the following text(GirlScript|Chennai) inside ```index.html```__

```html
    <title>GirlScript | Chennai</title>
````

**Comment by shreyakapoor08** [comment]
@smaranjitghose Yes, I will work on it

**Comment by smaranjitghose** [comment]
@shreyakapoor08 
Please do this in:
-  multiple PRs for each of the pages so that it is less cumbersome for me to review and suggest changes. 
- for a particular page, once you update the Guide.MD file, give an update PR for it at least after 2-3 days as we might have some bug fixes or enhancements for the same

**Comment by smaranjitghose** [comment]
@shreyakapoor08 I am closing this for now. Once we are done with all the major changes in the front-end part, we shall use [Sphinx](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) for professional documentation instead of READMEs or similar markdown files

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 I am closing this for now. Once we are done with all the major changes in the front-end part, we shall use [Sphinx](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) for professional documentation instead of READMEs or similar markdown files

Got it :)
