### ISSUE TITLE
Build and Use Appropiate GitHub Actions for this project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#10]

**Comment by anishagoswami167** [comment]
I want to work on this issue.

**Comment by siddhishree** [comment]
I would like to work on this.

**Comment by smaranjitghose** [comment]
@siddhishree 
@anishagoswami167  
Coordinate and try to come up with different GitHub actions for this. Make sure you give separate Pull Requests for each

**Comment by mySTRiouscoder** [comment]
@smaranjitghose  May i work on this as well?
