### ISSUE TITLE
Ensure the mobile responsiveness of the website without disturbing the current theme much

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#11]

**Comment by siddhishree** [comment]
I would like to work on this

**Comment by satvikchachra** [comment]
@smaranjitghose Sir, I would also like to work on this issue. If possible, please assign it to me also. Thanks. :)

**Comment by its-nothing-special** [comment]
@siddhishree Are you still working on this? If not, I would like to give it a shot!

**Comment by siddhishree** [comment]
@its-nothing-special yes, I am working.
