### ISSUE TITLE
The email input bar does not fit with themobile screen.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#113]
**Describe the bug**
The email input bar doesnt fit with the mobile screen.

**Expected behavior**
The email input bar should fit with the mobile screen.

**Screenshots**
![Screenshot from 2020-04-04 14-00-23](https://user-images.githubusercontent.com/55639487/78422494-50fd7980-767d-11ea-9b12-ff99c0a5aa5e.png)

**Desktop (please complete the following information):**
 - OS: [e.g.Ubuntu]
 - Browser [e.g. firefox

About me :-
GSSoC Aspirant

**Comment by aashimgarg** [comment]
I want to work on this issue.

**Comment by anushbhatia** [comment]
Go ahead and finish it within 3 days
