### ISSUE TITLE
Rendering Header Footer Dynamically 

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#116]
**Code Consistency**
There might be some changes in header and footer. So the changes have to be done in all the files where header and footer is written. Making those render dynamically using jQuery will save this and make the code more consistent.

**Solution Description**
A javaScript file will be executed before body load and will -
 - Append the footer at end of the body 
 - Prepend Header 
using jQuery.
Lines of code which will be reduced are  -
1) Scrolling Function 
![chennaiwebsiteRedundant1](https://user-images.githubusercontent.com/36301481/78423732-249a2b00-7686-11ea-9e5f-cf84649d8586.png)

2) Footer 
![chennaiwebsiteRedundant2](https://user-images.githubusercontent.com/36301481/78423741-34197400-7686-11ea-861d-11fa9e554ac1.png)

3) Header 

![chennaiwebsiteRedundantHeader2](https://user-images.githubusercontent.com/36301481/78423748-409dcc80-7686-11ea-999f-f0379694ad4b.png)

**Comment by smaranjitghose** [comment]
Awesome! Give a PR for this. The mentors will review it
