### ISSUE TITLE
the bottom to up button collides with items in mobile screen

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#121]
**Describe the bug**
the bottom to up button collides with items in mobile screen

**Screenshots**

![Screenshot from 2020-04-04 15-45-32](https://user-images.githubusercontent.com/55639487/78424481-83ae6e80-768b-11ea-8947-ce00887940ed.png)

**Comment by aashimgarg** [comment]
assign me this issue.

**Comment by anushbhatia** [comment]
how will you proceed?

**Comment by aashimgarg** [comment]
i will try to adjust its position.
