### ISSUE TITLE
GitHub Actions for the Project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#122]

**Comment by abhu-A-J** [comment]
@smaranjitghose Sir I want to try this?? May I know the actions required??

**Comment by aashimgarg** [comment]
@smaranjitghose i want too work on this issue

**Comment by smaranjitghose** [comment]
Well I don't have any specifications, you can use your creativity and come up with anything from continuous integration to simple messages on merge conflicts, 

Or perhaps use some of the existing ones out there

Although I would suggest try to make your own so that its a bonus on your portfolio 

All of you can give PRs to this issue
