### ISSUE TITLE
Fixing navbar and adding footer on Teams Page

### ISSUE THREAD

**Issue by goyalmuskan** [smaranjitghose/girlscript_chennai_website#145]
Currently, the team page doesn't have the updated navbar we are using and the footer is also missing, may I work on this issue? @smaranjitghose

**Comment by smaranjitghose** [comment]
Muskan, could you please check the current version. The recent PR to make it dynamic across all pages might have resolved it

**Comment by goyalmuskan** [comment]
Yes, sir, it's resolved. Though it's missing the social media icons in the footer, I'll just add them with my next PR for issue #6.
