### ISSUE TITLE
CSS minor issue Navbar

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#146]
**navbar shows text color black on initial**
A check is missing in app.js  while adding active class.
![initialLoad](https://user-images.githubusercontent.com/36301481/78459729-a024c800-76d8-11ea-8919-d2fe5bebed96.png)

**Comment by iBruceW** [comment]
Hi, I want to work on this issue. Please assign me on this issue.
