### ISSUE TITLE
Improvement of the Blogs Page

### ISSUE THREAD

**Issue by goyalmuskan** [smaranjitghose/girlscript_chennai_website#147]
I want to work on improving the current version of blogs.html. Please assign me the issue. @smaranjitghose

**Comment by iBruceW** [comment]
I write blogs too. Please assign me on this issue @smaranjitghose . I want to make that blog.html more appealing to the audience.

**Comment by smaranjitghose** [comment]
Muskan continue with your work on this, just comment on the Consolidated Issue I have raised for the Blog Page whenever you are free

**Comment by goyalmuskan** [comment]
Okay Sir @smaranjitghose
