### ISSUE TITLE
Improvement in Our Team Page

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#163]
**Improvements**
1) responsive view shows extra padding in heading
2) Id are used at multiple places, but Ids should be unique.
3) Animation on Team Avatar hover.
4) Proper margin between Avatar responsive design.

![image](https://user-images.githubusercontent.com/36301481/78473153-eff8a300-775b-11ea-92cf-60bdae26f021.png)

**Comment by smaranjitghose** [comment]
Work on #3 and #4 for now and comment on the Team Page issue highlighting the same
