### ISSUE TITLE
In announcements.html, content overlaps on resizing

### ISSUE THREAD

**Issue by BhuwanChandra** [smaranjitghose/girlscript_chennai_website#166]
In anouncements.html page, text in the upcoming events section overlaps. also, the padding in the upcoming event section is not proper.
**To Reproduce the bug**
1. Go to announcements.html
2. resize the window to mobile size
I would like to work on this issue. @smaranjitghose please assign me this issue.

**Comment by smaranjitghose** [comment]
Please check, its already fixed
