### ISSUE TITLE
Improvement required in Home Page

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#177]
**Describe the bug**
1. An unwanted text is visible on home screen.
![image](https://user-images.githubusercontent.com/31164665/78505058-6dd5a200-778e-11ea-9799-da312ed0c039.png)

2. The text written in the carousel does not make any sense. (WELCOME TO) what?
![image](https://user-images.githubusercontent.com/31164665/78505081-a7a6a880-778e-11ea-8662-fe517645b05d.png)

3. Alignment of text is not appropriate.
![image](https://user-images.githubusercontent.com/31164665/78505096-c9079480-778e-11ea-8564-b11a9f1308e2.png)

4.  The bold test needs to be pointer type and must redirect to the home page.
![image](https://user-images.githubusercontent.com/31164665/78505145-1552d480-778f-11ea-8524-3d1db58573b5.png)

5.  The moving cards under INITIATIVES sections need to be pointer type while hovering
![image](https://user-images.githubusercontent.com/31164665/78505162-361b2a00-778f-11ea-8d10-266d596b6f81.png)

6. The CSS of JOIN US button is not matching with the rest of the buttons.
![image](https://user-images.githubusercontent.com/31164665/78505199-78dd0200-778f-11ea-8674-d3b8f7d519b1.png)

**To Reproduce**
1. Go to Home Page
2. Click on portions as shown in the screenshots
3. Scroll down to the required section
4. See error as shown in the screenshot

**Expected behavior**
All these bugs needs to be corrected

**Screenshots**
All screenshots are being attached along with the problem statement

**Additional context**
I have found the above bugs in the website's home page and want to work on them in order to improve the website.

@smaranjitghose Kindly assign me this.

**Comment by shreyakapoor08** [comment]
@smaranjitghose Please have a look at this. Can I work on it?

**Comment by abhu-A-J** [comment]
Hello, @shreyakapoor08,  I'm actually working on the Home Page carousal part. I think @smaranjitghose Sir, will split this one to you on rest of the parts!! Thanks! We should wait for him to avoid any conflicting works on this one! Thanks!

**Comment by smaranjitghose** [comment]
@shreyakapoor08  Can you fix 4,5,6 while @abhu-A-J fixes 1,2,3

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 Can you please fix 4,5,6 while @abhu-A-J fixes 1,2,3

Sure :)

**Comment by shreyakapoor08** [comment]
@smaranjitghose Issues resolved Kindly check. :)
