### ISSUE TITLE
Broken Links in Footer 

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#178]
**Describe the bug**
The following links are not redirecting to the required pages.
1. Github Link
![image](https://user-images.githubusercontent.com/31164665/78505379-c443e000-7790-11ea-9d76-6110d5f0074f.png)

2. Linkedin Link
![image](https://user-images.githubusercontent.com/31164665/78505396-dd4c9100-7790-11ea-9aa4-e86dc9a197ef.png)

**To Reproduce**
1. Go to Footer
2. Click on Github and Linkedin icon
3. Scroll down to the bottom of the page

**Expected behavior**
On clicking the link it should redirect to the girlsscript github and linkedin page.

**Screenshots**
![image](https://user-images.githubusercontent.com/31164665/78505427-0f5df300-7791-11ea-8cd7-c559393a3085.png)

**Additional context**
Please assign me this issue.

**Comment by shreyakapoor08** [comment]
@smaranjitghose can I work on it ?

**Comment by smaranjitghose** [comment]
@shreyakapoor08 the team is working on shifting the GitHub and LinkedIn to new Ids, so its an internal issue
