### ISSUE TITLE
Improvements required in anouncements page.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#184]
1. the upcoming events do not have proper alignment .
2. On resizing the content goes out and this has to be fixed
3. excessive space at the left side.

![Screenshot from 2020-04-06 12-41-32](https://user-images.githubusercontent.com/55639487/78532429-dceddd80-7804-11ea-9d86-e6e9aa3aa846.png)

4. the buttons do not have format design throughout the page.

![Screenshot from 2020-04-06 12-49-54](https://user-images.githubusercontent.com/55639487/78532716-5980bc00-7805-11ea-801c-13fd349300c9.png)

**Comment by aashimgarg** [comment]
@smaranjitghose i want to work on this.

**Comment by smaranjitghose** [comment]
As per instructions in the slack channel, comment the bugs you want to fix in the particular issues of the pages instead of raising them separately
