### ISSUE TITLE
CSS changes required in the following issues.

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#187]

**Comment by aashimgarg** [comment]
i started before on working these issues.you can find other things to work on @shreyakapoor08 .

**Comment by shreyakapoor08** [comment]
> i started before on working these issues.you can find other things to work on @shreyakapoor08 .

@aashimgarg You might have started working on few but not all of them. 
And I have also checked the open issues before creating this one.
and I did not find any issue with the above changes that I mentioned :)
You might be mistaken :)

**Comment by aashimgarg** [comment]
@shreyakapoor08 i was working on the issue 5,7,8 which you mentioned.

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 i was working on the issue 5,7,8 which you mentioned.

@aashimgarg That is what I said :)
Anyway, I will edit and remove the issue 5, 7, 8 from here as you are working on them :)
Good Luck!

**Comment by shreyakapoor08** [comment]
@aashimgarg I have removed it from here. It would be great if you could remove your comments from here so that mentors won't get confused with it. As i have edited the issue and removed the once which you mentioned.
