### ISSUE TITLE
CSS issues in the below mentioned positions

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#188]
**Describe the bug**
1. The position of ANNOUNCEMENT in carousel is not correctly placed
![image](https://user-images.githubusercontent.com/31164665/78536426-74eec580-780b-11ea-98a4-887fd4138abf.png)

2. The contactus button is not matching with the other buttons
![image](https://user-images.githubusercontent.com/31164665/78536493-8e900d00-780b-11ea-9c5b-4cbeebebbd4b.png)

3. This page is opened after clicking contactus button. The following cards has inappropriate css color while hovering on it.
![image](https://user-images.githubusercontent.com/31164665/78536664-d57e0280-780b-11ea-98c2-6b74d56c2acd.png)

4. This page is opened after clicking contactus button. The following button has inappropriate CSS.
![image](https://user-images.githubusercontent.com/31164665/78536724-ed558680-780b-11ea-8b0d-4bbc22eb82ec.png)

5. Excessive space at the top of team page
![image](https://user-images.githubusercontent.com/31164665/78538688-03b11180-780f-11ea-92e1-6cc4572e346a.png)

**To Reproduce**
1. Go to the pages as instructed above
2. Click on the portions as mentioned above
3. Scroll to the parts as mentioned above

**Expected behavior**
The above issues should be corrected and follow a systematic css all over 

**Additional context**
@smaranjitghose Can I work on the above mentioned issues ?

**Comment by shreyakapoor08** [comment]
@smaranjitghose Hey, Can I work on the above mentioned issues ? :)

**Comment by smaranjitghose** [comment]
Sure!.

Also try to give multiple PRs so that it helps you on scoreboard too

**Comment by shreyakapoor08** [comment]
Got it ☺ Thanks 
I will raise 2 PRs for this one ☺

**Comment by smaranjitghose** [comment]
Shreya you continue with the bug fixes, I am consolidating the issues for each page, whenever you are free do comment there just for the sake that others don't assume that it's available

**Comment by shreyakapoor08** [comment]
@smaranjitghose Thankyou, I will do that☺
