### ISSUE TITLE
content of navbar slides down on resizing.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#189]
** Describes the bug**

The content of the navbar slides on all the pages before the toggler icon appears on the screen.

**screenshots**

![Screenshot from 2020-04-06 14-36-32](https://user-images.githubusercontent.com/55639487/78542406-c0f23800-7814-11ea-868a-d737ef0562d3.png)

**expected behavior**

![Screenshot from 2020-04-06 14-37-35](https://user-images.githubusercontent.com/55639487/78542462-d4050800-7814-11ea-9417-1c0b98abf059.png)

**Comment by aashimgarg** [comment]
@smaranjitghose i want too work on this.

**Comment by smaranjitghose** [comment]
Go ahead
