### ISSUE TITLE
Carousel conntent error.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#190]
**Describe the bug**

Carousel content hides on resizing and mobile view it display goes off.

**Screenshots**

![Screenshot from 2020-04-06 15-20-00](https://user-images.githubusercontent.com/55639487/78546053-72e03300-781a-11ea-8ac9-349bf5f7c702.png)

![Screenshot from 2020-04-06 15-20-05](https://user-images.githubusercontent.com/55639487/78546058-75db2380-781a-11ea-94e7-b1f3ea25814c.png)

**Comment by shreyakapoor08** [comment]
#188 already working on it☺
