### ISSUE TITLE
Team Page 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#191]
Please share a screenshot with an elaborate description of what part you want to improve on or any bug you wish to fix

**Comment by Satyam3976** [comment]
Please Assign me this issue, I want to work on this @smaranjitghose

**Comment by shwetagurnani** [comment]
Please assign me this issue.I want to work on it.

**Comment by shreyakapoor08** [comment]
@smaranjitghose hey, kindly assign this to me☺ as discussed

**Comment by smaranjitghose** [comment]
Please mention what you want to contribute with a possible screenshot

**Comment by ashishnagpal2498** [comment]
**Improvements**
1) responsive view shows extra padding in heading
2) Id are used at multiple places, but Ids should be unique.
3) Animation on Team Avatar hover.
4) Proper margin between Avatar responsive design.

![image](https://user-images.githubusercontent.com/36301481/78473153-eff8a300-775b-11ea-92cf-60bdae26f021.png)

**Comment by smaranjitghose** [comment]
@ashishnagpal2498 please collaborate with @shreyakapoor08 for the changes when you two give your PRs

**Comment by abhu-A-J** [comment]
Part 3: not taken into consideration above

I would like to collaborate with other above and do the following:
- Fix the navbar and make it consistent with other pages
- Bring in the go to top button and get it functioning on the page
- The heading and sub headings are not consistent with other pages in terms of it looks and style (it kinda looks completely different from other pages)
 I think rest of them are handled by people above!

**SCREENSHOTS:**
No go to top button ( can be seen in below screenshots itself.

**No consistent navbar:** 
![Screenshot (90)](https://user-images.githubusercontent.com/49617450/78652596-8dc8ab00-78df-11ea-80e6-f3be05c3b8bb.png)

**No consistent heads and subhead:**
![Screenshot (91)](https://user-images.githubusercontent.com/49617450/78652803-d718fa80-78df-11ea-84da-0e8bb0e06a64.png)

I considered  I'd like to work on it! Thank you!

**Comment by abhu-A-J** [comment]
> **Part 3:** not taken into consideration above
> 
> I would like to collaborate with other above and do the following:
> 
> * Fix the navbar and make it consistent with other pages
> * Bring in the go to top button and get it functioning on the page
> * The heading and sub headings are not consistent with other pages in terms of it looks and style (it kinda looks completely different from other pages)
>   I think rest of them are handled by people above!
> 
> **SCREENSHOTS:**
> No go to top button ( can be seen in below screenshots itself.
> 
> **No consistent navbar:**
> ![Screenshot (90)](https://user-images.githubusercontent.com/49617450/78652596-8dc8ab00-78df-11ea-80e6-f3be05c3b8bb.png)
> 
> **No consistent heads and subhead:**
> ![Screenshot (91)](https://user-images.githubusercontent.com/49617450/78652803-d718fa80-78df-11ea-84da-0e8bb0e06a64.png)
> 
> **If considered valid I'd like to work on it! Thank you!**

Mentors is this still open to do?

**Comment by goyalmuskan** [comment]
Sir, may I work on this? The footer of this page isn't consistent with the other pages. @smaranjitghose

**Comment by anushbhatia** [comment]
Go ahead and try ti complete this eithin 3 days

**Comment by goyalmuskan** [comment]
> Go ahead and try ti complete this eithin 3 days

Yes, sure!

**Comment by shreyakapoor08** [comment]
@anushbhatia @smaranjitghose 
Their is no margin between the header and the starting of body
![image](https://user-images.githubusercontent.com/31164665/78885790-cf418d80-7a7a-11ea-865a-6f4c39461e57.png)

Can I work on this ?

**Comment by smaranjitghose** [comment]
sure!

**Comment by smaranjitghose** [comment]
@shreyakapoor08 take the google drive link from @anushbhatia and update the board members pictures

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 take the google drive link from @anushbhatia and update the board members pictures

@anushbhatia Please send the link 😊

**Comment by smaranjitghose** [comment]
@anushbhatia @shreyakapoor08 Please don't share that here. Use slack for it 😅

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 take the google drive link from @anushbhatia and update the board members pictures

Done, Please check
