### ISSUE TITLE
Announcement Page 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#192]

**Comment by Satyam3976** [comment]
Can I work on this issue @smaranjitghose

**Comment by shreyakapoor08** [comment]
@smaranjitghose hey, assign me as discussed ☺

**Comment by shwetagurnani** [comment]
I want to work on this issue.Please assign it to me:)

**Comment by shwetagurnani** [comment]
I want to work on this issue.Please assign it to me:)

**Comment by smaranjitghose** [comment]
Please describe what you all want to improve with screenshots.
Also, make sure the ones assigned collaborate with each other so that there is no merge conflicts

**Comment by ashishnagpal2498** [comment]
Cleaning -  Removing 
1) Inline CSS
2) Deprecated tags like font, center etc.

**Comment by BhuwanChandra** [comment]
@smaranjitghose I would like to work on these following issues. please assign me.

1. on clicking read more on upcoming events on the next page have these resizing issues in the schedule section
![Capture3](https://user-images.githubusercontent.com/46065877/78561315-235b3080-7835-11ea-9d86-988e3882b4c2.JPG)

2. on clicking read more on upcoming events on the next page have there are resizing issues with about section
![Capture2](https://user-images.githubusercontent.com/46065877/78562137-839ea200-7836-11ea-84a9-64aadef8d4b4.JPG)

3. on clicking read more on upcoming events on the next page there is no navbar
![Capture](https://user-images.githubusercontent.com/46065877/78562492-14757d80-7837-11ea-8f2a-dc2631b6dccb.JPG)

4. on clicking read more on upcoming events on the next page there is no footer
![Capture1](https://user-images.githubusercontent.com/46065877/78562513-1d664f00-7837-11ea-8968-cf236d02c266.JPG)

**Comment by smaranjitghose** [comment]
@goyalmuskan Please point out the enhancements or the bugs you wish to work on

**Comment by goyalmuskan** [comment]
1. Remove carousel and do something else in its place -
![Screenshot (83)](https://user-images.githubusercontent.com/47412347/78713681-47536a80-7938-11ea-8534-c809a7799f73.png)

2. Improve CSS of these cards -
![Screenshot (84)](https://user-images.githubusercontent.com/47412347/78713765-64883900-7938-11ea-8e35-a55d522d703b.png) 

3. Improve CSS -
![Screenshot (85)](https://user-images.githubusercontent.com/47412347/78713829-79fd6300-7938-11ea-8621-97cdc4be5009.png)

4. Improve this entire section, doesn't go well with the website -
![Screenshot (86)](https://user-images.githubusercontent.com/47412347/78713903-98fbf500-7938-11ea-831d-cb14860a0e19.png)

**Comment by smaranjitghose** [comment]
Cool..go ahead
