### ISSUE TITLE
Achievements Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#196]
Please share a screenshot with an elaborate description of what part you want to improve on or any bug you wish to fix

**Comment by BhuwanChandra** [comment]
@smaranjitghose I would like to work on this. please assign me.

**Comment by aashimgarg** [comment]
Hey @smaranjitghose i want too work on this issue.

![Screenshot from 2020-04-06 13-05-23](https://user-images.githubusercontent.com/55639487/78553597-29e2ab80-7827-11ea-9021-426e0312da9a.png)
excessive space given.

Content not aligned.

![Screenshot from 2020-04-06 13-05-35](https://user-images.githubusercontent.com/55639487/78553607-30712300-7827-11ea-867d-7f2ca0fd5088.png)

excess margins on both sides.
![Screenshot from 2020-04-06 13-06-28](https://user-images.githubusercontent.com/55639487/78553622-35ce6d80-7827-11ea-9df8-bb1a861a0f0f.png)

**Comment by ashishnagpal2498** [comment]
Cleaning -  Removing 
1) Inline CSS
2) Deprecated tags like font, center etc.

**Comment by smaranjitghose** [comment]
@aashimgarg and @ashishnagpal2498 Go ahead and please collaborate on the issues you solve

**Comment by BhuwanChandra** [comment]
@smaranjitghose I would like to work on these issues. please assign me.

1. button colors and style is not matching with the theme of the website
![Capture4](https://user-images.githubusercontent.com/46065877/78563658-f6a91800-7838-11ea-9ead-d3382309dd7e.JPG)

2. back to top button is hiding behind the content
![Capture5](https://user-images.githubusercontent.com/46065877/78563712-09bbe800-7839-11ea-9137-1dead3bc310f.JPG)

**Comment by shreyakapoor08** [comment]
@smaranjitghose @anushbhatia 

*On clicking anywhere on the card it is opening the events page. It should only be opened when clicked on the read more button.
![image](https://user-images.githubusercontent.com/31164665/78886076-4119d700-7a7b-11ea-9c0c-cc1136ba57a7.png)

Can I work on this ?

**Comment by smaranjitghose** [comment]
Ya, fix that please
