### ISSUE TITLE
Make the theme of the website more even

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#2]
# Sections of the website:
- Home 
- Annoucements 
- Achievements 
- Team 
- Contact Us

**Comment by goyalmuskan** [comment]
Please assign it to me!

**Comment by Yashank18** [comment]
Please assign it to ne. I have some ideas.

**Comment by shreoshi-roy** [comment]
@smaranjitghose please assign this issue to me, i am interested in working on this.

**Comment by bharati-21** [comment]
I'm interested in working on this too! In case any work is pending, please assign it to me as well.
