### ISSUE TITLE
UI/UX Tasks

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#213]
- Create a custom logo for the project that represents the concepts of open-source,code and the actual GirlScript Foundation logo
- Create a preview image for the repository (1280×640) with the key ideas mentioned above

**Comment by habeeba-naaz** [comment]
I am interested to work...if possible please assign this to me

**Comment by aashimgarg** [comment]
I am interested in this work.

**Comment by habeeba-naaz** [comment]
Thank you for assigning...I’ll start working on it

**Comment by smaranjitghose** [comment]
Please make sure that you design it from scratch. We don't want any copyright issues here

**Comment by anushbhatia** [comment]
Respond back to me on slack when done with design don't give a PR directly.

**Comment by aashimgarg** [comment]
Ok @smaranjitghose

**Comment by habeeba-naaz** [comment]
![GirlScript-Chennai Logo](https://user-images.githubusercontent.com/29932609/78782476-18f18180-7970-11ea-8355-6adccca148cc.png)

**Comment by habeeba-naaz** [comment]
![GSChennaiLogo](https://user-images.githubusercontent.com/29932609/78789554-48f25200-797b-11ea-842b-e50d95d9d5cc.png)

**Comment by Adyasha8105** [comment]
@smaranjitghose Can I work on this issue?

**Comment by smaranjitghose** [comment]
@anushbhatia is supervising this. Please have a talk with him on the slack channel regarding this

**Comment by smaranjitghose** [comment]
@Adyasha8105 
 Go to medium.com/techequilla and see the first blog there for the Shots series.
Can you design some cover image templates for it that we can officially use for the future blogs
If you wish you can take images from UnSplash but please do not take some other's blogs images directly, we don't want copyright issues here

**Comment by aashimgarg** [comment]
![Screenshot from 2020-04-10 08-37-41](https://user-images.githubusercontent.com/55639487/78958809-cac2b680-7b06-11ea-962b-9d8c10ff79ab.png)

@anushbhatia have a look. :)

**Comment by anushbhatia** [comment]
![1586519917684](https://user-images.githubusercontent.com/40017559/78989262-c58a5980-7b50-11ea-8b44-843b4a44477d.png)
make same for our website

**Comment by Adyasha8105** [comment]
@anushbhatia  Can I work on it?
