### ISSUE TITLE
email input not working propery in contactUs page

### ISSUE THREAD

**Issue by aman-atg** [smaranjitghose/girlscript_chennai_website#221]
**Describe the bug**
As the email field looses focus its "placeholder" overlaps with the input's value

**To Reproduce**
1. Go to 'http://127.0.0.1:5500/contactUs.html'
2. Click on 'Email Field'
3. Enter any invalid email

**Expected behavior**
Red border and no change in Placeholder's position

**Screenshots**
![ss](https://user-images.githubusercontent.com/28243942/78803289-6f94a500-79dc-11ea-8ae1-5b0cb2fd41f5.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by aman-atg** [comment]
I would like to work on this.

**Comment by smaranjitghose** [comment]
Don't raise separate issues. Please comment on the associated pages's issue
