### ISSUE TITLE
Fix images and css files 

### ISSUE THREAD

**Issue by Aman-Codes** [smaranjitghose/girlscript_chennai_website#23]
@smaranjitghose  I am a GSSOC participant and I would like to work on these issues and remove the errors from the console in this project.

- Image name in the html file is not correct so it is not loaded properly.
- owl.carousel.min.css file is not present in the css folder.
- Alt tag for images is not present.
- Adding images from other urls into the asset folder.
- font awesome file not loaded properly.

![pic2](https://user-images.githubusercontent.com/54680709/76741360-70e40080-6795-11ea-956f-a46a89b00290.PNG)

**Comment by smaranjitghose** [comment]
Please check out the latest version of the codebase, This has been already improved a few days back
