### ISSUE TITLE
Rearrange the Files

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#237]
@smaranjitghose I just want to arrange these files and put them at specific folders.
Can you assign this part to me?

**Comment by smaranjitghose** [comment]
Cool!.
But make sure you make a Guide.MD file where you elaborately describe the organization of the files as well as what each is related to

**Comment by Adyasha8105** [comment]
Okay :)

**Comment by Adyasha8105** [comment]
> Cool!.
> But make sure you make a Guide.MD file where you elaborately describe the organization of the files as well as what each is related to

Can you ellaborate???

**Comment by smaranjitghose** [comment]
@Adyasha8105 I would suggest doing this after 15th April

**Comment by Adyasha8105** [comment]
@smaranjitghose I have already made a PR.

**Comment by Adyasha8105** [comment]
@smaranjitghose Just Inform me when I have to do, I will surely do it.

**Comment by smaranjitghose** [comment]
Once, the front end is finalized and all the code is well documented. We can have this done @Adyasha8105. For now, I am closing this issue

**Comment by smaranjitghose** [comment]
Push all changes to master. Make sure the documentation is synchronous with this!

**Comment by Adyasha8105** [comment]
> Push all changes to master. Make sure the documentation is synchronous with this!

okay @smaranjitghose
