### ISSUE TITLE
ContactUs Page

### ISSUE THREAD

**Issue by goyalmuskan** [smaranjitghose/girlscript_chennai_website#241]
I want to improve the CSS of the form and make it consistent with the other pages.
May I work on this issue? @smaranjitghose

**Comment by rajraman786** [comment]
sir, I want to add an attractive related image at the top of the page. change the style of the form, configure submit button and add any type of captcha before submit of form
may i work on this.

**Comment by smaranjitghose** [comment]
@rajraman786
-  Please don't give a PR by adding an image on the top. If you wish to do it, first give the screenshots of the proposed changes regarding it here
- Centre align the ```Send Message``` button
- Add the captcha verification feature

**Comment by rajraman786** [comment]
@smaranjitghose 
sir,
   here is the screenshot of  captcha verification feature
  and Centre align the Send Message button.
![cs2](https://user-images.githubusercontent.com/55931033/79037379-fcfb1380-7bed-11ea-8eab-db3de9fe14b3.PNG)

and here is screenshot of image added on the top.
![cs1](https://user-images.githubusercontent.com/55931033/79037401-316ecf80-7bee-11ea-9b80-fbfcfe8d4046.PNG)
and here is added text.
![cs3](https://user-images.githubusercontent.com/55931033/79037412-48152680-7bee-11ea-9050-7d8c93db970f.PNG)

**Comment by rajraman786** [comment]
@smaranjitghose 
sir, 
    kindly take a look on these screenshot. and suggest me
   with which features i give the PR.

**Comment by anushbhatia** [comment]
Which capache have u used? And try to incorporate it within design like a field for that entry.

**Comment by rajraman786** [comment]
@anushbhatia 
here I used numbered captcha and it is suitable with website CSS.

here is the screenshot.
![cs4](https://user-images.githubusercontent.com/55931033/79042758-e8cc0c00-7c17-11ea-8691-6f82b7f8ec60.PNG)

and kindly comment about the image part.
it seems good or I have to remove it.

**Comment by anushbhatia** [comment]
Have the input field same as that of the other fields

**Comment by rajraman786** [comment]
@anushbhatia 
  sir,
      may you describe more.
      what i do.

**Comment by anushbhatia** [comment]
Jave u seen the other input format on screen. I want the input format the same. Rest everything is great

**Comment by rajraman786** [comment]
@anushbhatia 
sir,
    as you told make input format of captcha same as other input formats.
but it doesn't suit the form. it may arise another issue.
this CSS of the input format of captcha fit with the form.

here is the screenshot of the form

![cs5](https://user-images.githubusercontent.com/55931033/79051648-e20cbb80-7c4e-11ea-9a0b-62df8fe68395.PNG)
now if you say I put the PR

**Comment by anushbhatia** [comment]
ok

**Comment by rajraman786** [comment]
@anushbhatia 
sir, 
     i added the PR please check.

**Comment by smaranjitghose** [comment]
I guess this is done. So this is closed
