### ISSUE TITLE
Padding issues in team page and unexpected changes in navbar.

### ISSUE THREAD

**Issue by garimasingh128** [smaranjitghose/girlscript_chennai_website#253]
**Describe the bug**
The team page features the pictures of the teammates in which animation is buggy due to padding issues. The navbar changes all the navbar items to bold text when we click on Announcements, Our Team and Our Achievements. And other buggy UI issues.

**To Reproduce**
1. Go to 'Home'
2. Observe the navbar.
3. Now go to any of the following: Announcements, Our Team and Our Achievements.
4. See changes in the navbar.

**Screenshots**
![Screenshot (396)](https://user-images.githubusercontent.com/44302373/78948239-4449ad00-7ae5-11ea-859e-6cd342359f38.png)
![Screenshot (398)](https://user-images.githubusercontent.com/44302373/78948247-49a6f780-7ae5-11ea-9503-82ac3300535a.png)
![Screenshot (397)](https://user-images.githubusercontent.com/44302373/78948260-54fa2300-7ae5-11ea-83f7-f753bb722493.png)
![Screenshot (399)](https://user-images.githubusercontent.com/44302373/78948310-7824d280-7ae5-11ea-9109-45c88cabb1b6.png)
![Screenshot (400)](https://user-images.githubusercontent.com/44302373/78948322-7f4be080-7ae5-11ea-8532-d5e239d6d43c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - Chrome

**Comment by garimasingh128** [comment]
@smaranjitghose Kindly allow me to fix these small UI bugs if they're well-considerable.

**Comment by smaranjitghose** [comment]
@garimasingh128 in your PR, please remove the ```show all``` button as well as the associated hidden section for the Board  Members

**Comment by smaranjitghose** [comment]
@garimasingh128 Please continue with this issue after incorporating the recent changes

**Comment by garimasingh128** [comment]
Okay sir.
