### ISSUE TITLE
Create a vector for offline or error 404 screen

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#256]
Take ideas from 
[Link 1](https://dev.to/) (Use it in offline mode)
[Link 2](https://www.searchenginejournal.com/404-page-examples/211154/)
[Link 3](https://optinmonster.com/best-404-page-examples/)

**If you need any vector or any ideas you feel free to contact any mentor.**

**Comment by aashimgarg** [comment]
Can i work on this issue?

**Comment by Adyasha8105** [comment]
@anushbhatia  May I?
