### ISSUE TITLE
Bugs in Achievements Page and Related Enhancements

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#258]
# 1. Fix the spacing and alignment

![achievments](https://user-images.githubusercontent.com/46641503/78990441-118acd80-7b54-11ea-8872-63ad2a2d5829.png)

# 2  Projects Section
![Annotation 2020-04-10 175110](https://user-images.githubusercontent.com/46641503/78990585-6cbcc000-7b54-11ea-9297-bcec4c9dc383.png)

- Link Text overflows.
- Instead have a button that redirects to GitHub. (View or Check it on GitHub)
- Change transition effect as the arrow on the top messes up the creator name
- Instead of the demo content and pictures, fill in actual project details. For now, make use of these:
  - https://github.com/smaranjitghose/smaransnotepad
  - https://github.com/smaranjitghose/DeepPixel
  - https://github.com/smaranjitghose/AutoPromPicker
  - https://github.com/smaranjitghose/smileplease
  - https://github.com/smaranjitghose/sketchPy
  - https://github.com/smaranjitghose/floodater

**Comment by Aman-Codes** [comment]
@smaranjitghose  I would like to work on this issue. Please assign me this issue.

**Comment by smaranjitghose** [comment]
@Aman-Codes Work on #1 first, get the PR merged and then comment here for #2

**Comment by goyalmuskan** [comment]
May I work on 2nd? @smaranjitghose

**Comment by shreyakapoor08** [comment]
@smaranjitghose Can I work on this ?

**Comment by smaranjitghose** [comment]
@Aman-Codes is doing #1 and @goyalmuskan  is doing #2 after their PRs, you can add some animations or hover effect to the pictures

**Comment by smaranjitghose** [comment]
@Aman-Codes when you fix the spacing please ensure you have already incorporated the changes @goyalmuskan made, we don't want the same thing to be done again

**Comment by anushbhatia** [comment]
Reduce the shadow in these and add a lighter colour and have a button to read more.
![1586632693809](https://user-images.githubusercontent.com/40017559/79052921-4e8bb880-7c57-11ea-9a98-d7bf8ccb72d2.png)

**Comment by shreyakapoor08** [comment]
![image](https://user-images.githubusercontent.com/31164665/79064625-1e303280-7cc8-11ea-95aa-d10b7d23d337.png)

@smaranjitghose Can I add the content to this one. and remove the dummy content ?

**Comment by shreyakapoor08** [comment]
@smaranjitghose 
While clicking on these it redirects to the top of the page which should not be the case
![image](https://user-images.githubusercontent.com/31164665/79064767-56844080-7cc9-11ea-9e7d-d3ed62d2c819.png)
