### ISSUE TITLE
Add Code_Of_Conduct.md

### ISSUE THREAD

**Issue by Aman-Codes** [smaranjitghose/girlscript_chennai_website#259]
**Is your feature request related to a problem? Please describe.**
No Code_Of_Conduct.md file present and link in readme.md does not work

**Describe the solution you'd like**
As a GSSOC participant I would like to add Code_Of_Conduct.md file and update Readme.md.

**Additional context**
![broken link](https://user-images.githubusercontent.com/54680709/78990347-dab4b780-7b53-11ea-987b-d89d2f27813e.PNG)

@smaranjitghose Please assign me this issue.

**Comment by Aman-Codes** [comment]
@smaranjitghose Can you please share your email id where participants can report any unacceptable behavior.

**Comment by Kuljeet-123** [comment]
@smaranjitghose Can I work on this issue??

**Comment by smaranjitghose** [comment]
@Aman-Codes just give the PR for it, I'll edit it

**Comment by smaranjitghose** [comment]
@
