### ISSUE TITLE
Our Blog section

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#262]
**Describe the bug**
Improving CSS

**To Reproduce**
1. Go to Our Blog
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/31164665/79002487-368c3a00-7b6e-11ea-8a58-387e30d381f8.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by shreyakapoor08** [comment]
@smaranjitghose Can I work on this ?

**Comment by smaranjitghose** [comment]
Definitely change that. If required you can remove it because when the page is loaded, it seems to be a different section itself
