### ISSUE TITLE
Code Quality Improvement

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#263]
**CSS can be defined once and can be reused at different places**
There is a lot of redundancy I see in all the file and code is bit messy which I think can be refactored.
1. Improving CSS -
2. Removing deprecated tags like center,font etc.
3. Improving code convention - using correct tags - There are places where '<p>' tag is used for buttons which don't make any sense. 
4. Using script tags between html reduces the code readability.
Files handled -
- index.html
- announcement
- our team
- events
- style.css
- achievement 
- blogs
- contactUs
I would solely like to work on this issue @smaranjitghose . Kindly assign me this issue.

**Screenshots**
index file -
![image](https://user-images.githubusercontent.com/36301481/79002432-1b212f00-7b6e-11ea-8110-a5493955a052.png)

announcement page -
![image](https://user-images.githubusercontent.com/36301481/79002476-31c78600-7b6e-11ea-9714-6742f216fd0b.png)

**Comment by smaranjitghose** [comment]
Cool! Work on this. But please don't give a PR for this issue until 15th, we have some more changes to make after which you can proceed

**Comment by ashishnagpal2498** [comment]
Okay, let all the changes be done, then I can work on it.

**Comment by ashishnagpal2498** [comment]
Can I start working on this now @smaranjitghose ?

**Comment by smaranjitghose** [comment]
I guess this issue is completed @ashishnagpal2498 or should I keep it open?

**Comment by ashishnagpal2498** [comment]
No , it is not yet completed @smaranjitghose . CSS of whole project is left.
