### ISSUE TITLE
Footer Fix for all pages

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#274]
**Description of the enhancement**
A clear and concise description of what the problem you wish to solve or any enhancement you wish to do for the project

**Screenshots**
![footer](https://user-images.githubusercontent.com/46641503/79026909-e336dd80-7ba7-11ea-9a84-98de63108091.png)
- Shift the GirlScipt Icon to the left
- Instead of ```Copyright...``` , make it ```Made with  ♥  ```

**Comment by shreyakapoor08** [comment]
can I work on this? @smaranjitghose
