### ISSUE TITLE
Button Enhancement all over the project 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#286]
Use the same kind of drop shadow all over the project 
Have round rectangular corners
radius: 6-8
x:0
y:3
b:6

Before giving a pr just send the image here

**Comment by Adyasha8105** [comment]
> Use the same kind of drop shadow all over the project
> Have round rectangular corners
> radius: 6-8
> x:0
> y:3
> b:6
> 
> Before giving a pr just send the image here

Can I?

**Comment by ashishnagpal2498** [comment]
@anushbhatia @smaranjitghose  Can I work on this ?

**Comment by ashishnagpal2498** [comment]
@anushbhatia -  radius 10px 
box-shadow -0 3 6
![image](https://user-images.githubusercontent.com/36301481/79065211-4588fe80-7ccc-11ea-9a51-58a68a3d0934.png)
Is this fine?
