### ISSUE TITLE
Card Optimization in achievements page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#287]
![1586633754706](https://user-images.githubusercontent.com/40017559/79053283-c8bd3c80-7c59-11ea-8352-898ca1bb2dbd.png)
Use Proper Symbols in this.
Remove the red line present in the card and Girlscript Chennai heading

**Comment by Adyasha8105** [comment]
> ![1586633754706](https://user-images.githubusercontent.com/40017559/79053283-c8bd3c80-7c59-11ea-8352-898ca1bb2dbd.png)
> Use Proper Symbols in this.
> Remove the red line present in the card and Girlscript Chennai heading

can I work on this?

**Comment by ashishnagpal2498** [comment]
@anushbhatia @smaranjitghose Can I work on this ? :)
