### ISSUE TITLE
Improvement in Contact us page.

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#290]
I want to improve the CSS of contact us page. It is looking empty as compared to other pages.
![image](https://user-images.githubusercontent.com/36301481/79054871-2e172a80-7c66-11ea-87c1-0ccb3cf00773.png)

**Comment by anushbhatia** [comment]
Don't clutter the ui then

**Comment by Kashish-max** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by anushbhatia** [comment]
What all changes you want to make

**Comment by smaranjitghose** [comment]
Are there any further changes for the contact page?

**Comment by Kashish-max** [comment]
yes

**Comment by Kashish-max** [comment]
yes , you can close this issue
