### ISSUE TITLE
Some pages donot have dynamic footer

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#291]
Footer code can be removed as footer is defined in app.js dynamically.
![image](https://user-images.githubusercontent.com/36301481/79055061-8d296f00-7c67-11ea-9ff8-1e7e3d81aa26.png)

**Comment by anushbhatia** [comment]
Linos are incorrect change them too add correct links and before making a pr sent changes here.

**Comment by ashishnagpal2498** [comment]
Hi @anushbhatia , Kindly provide the correct links of girlScript-chennai social media.
