### ISSUE TITLE
Improvement in our achievement page

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#293]
The card overlaps on show more button.
Before 
![image](https://user-images.githubusercontent.com/36301481/79055212-df1ec480-7c68-11ea-92e6-ef65482b4848.png)

After card opens
![image](https://user-images.githubusercontent.com/36301481/79055219-e8a82c80-7c68-11ea-855f-d53ee50365b4.png)

**Comment by anushbhatia** [comment]
Already an issue exaists for this
