### ISSUE TITLE
Redesingning the contactUs form and map 

### ISSUE THREAD

**Issue by arpita-in** [smaranjitghose/girlscript_chennai_website#30]
- Adding effects to buttons and input boxes of form 

- Aligning the map alongside the form for dense look

**Are you working on this issue ?
Yes**

**Comment by scortier** [comment]
May u please assign me this issue, I want to work on this part.

**Comment by shash137** [comment]
@smaranjitghose I want to work on this issue.

**Comment by Mustafiz04** [comment]
I would like to work on this issue if work hasn't completed yet

**Comment by abhishekgupta368** [comment]
Hey, can I do it?

**Comment by shreyakapoor08** [comment]
@smaranjitghose Can I work on this issue ?

**Comment by smaranjitghose** [comment]
@shreyakapoor08 Sure Give a PR, I will review it accordingly
