### ISSUE TITLE
Announcement Page Enhancement

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#301]
The cards are looking empty and enlarged as compared to the content
![image](https://user-images.githubusercontent.com/31164665/79064886-1e313200-7cca-11ea-87e3-d42c48f7f1ef.png)

@smaranjitghose @anushbhatia  Can I work on this ? :)

**Comment by shreyakapoor08** [comment]
@smaranjitghose While clicking on the first card the button(Read More) design is different than the other 2
![image](https://user-images.githubusercontent.com/31164665/79064917-5afd2900-7cca-11ea-9fbe-1584406f0938.png)

**Comment by anushbhatia** [comment]
Already #258 exists
