### ISSUE TITLE
Making Announcement Page Responsive

### ISSUE THREAD

**Issue by goyalmuskan** [smaranjitghose/girlscript_chennai_website#303]
**Description of the enhancement**
The current version of the announcement page is not responsive.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![Screenshot (134)](https://user-images.githubusercontent.com/47412347/79065285-d7910700-7ccc-11ea-9cf9-0a95f0ffa21c.png)
![Screenshot (133)](https://user-images.githubusercontent.com/47412347/79065289-d95aca80-7ccc-11ea-925b-feb56678b5ac.png)
![Screenshot (132)](https://user-images.githubusercontent.com/47412347/79065290-d9f36100-7ccc-11ea-8216-002c653afc9a.png)

**Comment by goyalmuskan** [comment]
May I work on this? @smaranjitghose

**Comment by Kashish-max** [comment]
Sir May I also work on this?

**Comment by anushbhatia** [comment]
it's been 4 days now @goyalmuskan now I will assign it to @Kashish-max

**Comment by goyalmuskan** [comment]
Sorry, I was busy with a personal project. It's fine, @Kashish-max can work. 👍🏻
