### ISSUE TITLE
Fixing the footer.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#308]
The footer looks weird.

![Screenshot from 2020-04-12 22-28-27](https://user-images.githubusercontent.com/55639487/79074951-1cd52900-7d0d-11ea-98e5-19680c0acca7.png)

Browser: Firefox

**Comment by shreyakapoor08** [comment]
@anushbhatia The whole code has been disoriented, and that is why the footer along with the whole website is messed.
