### ISSUE TITLE
Blog page content issues.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#314]
As we resize the window the content we start to loose the content. Instead we can use overflow property for this.

What is your opinion @anushbhatia @smaranjitghose

**Comment by aashimgarg** [comment]
![Screenshot from 2020-04-13 11-01-39](https://user-images.githubusercontent.com/55639487/79094812-5130ff80-7d76-11ea-8ccd-f8ef91a96d7e.png)

![Screenshot from 2020-04-13 11-02-20](https://user-images.githubusercontent.com/55639487/79094822-5aba6780-7d76-11ea-9e28-0e8eb8c3b0a3.png)

**Comment by anushbhatia** [comment]
We have used the medium's function u can use overflow but then it will cause a change in the style.
