### ISSUE TITLE
Responsive Our Team

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#324]
In small screen the images are not aligned
![image](https://user-images.githubusercontent.com/31164665/79129688-4badd680-7dc3-11ea-85c4-de5f5dd3ee22.png)

![image](https://user-images.githubusercontent.com/31164665/79129725-5a948900-7dc3-11ea-8915-2345a76f81aa.png)

@smaranjitghose @anushbhatia Can I work on it?

**Comment by Kashish-max** [comment]
Sir I would like to work on this issue, please assign this to me.

**Comment by Kashish-max** [comment]
I unassigned myself by mistake please reassign
