### ISSUE TITLE
Responsive Footer

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#325]
I want to make the footer responsive.
![2020-04-13 (18)](https://user-images.githubusercontent.com/54095539/79139494-0c3bb600-7dd4-11ea-8dcc-9b49489e99ec.png)

**Comment by Adyasha8105** [comment]
> I want to make the footer responsive.
> ![2020-04-13 (18)](https://user-images.githubusercontent.com/54095539/79139494-0c3bb600-7dd4-11ea-8dcc-9b49489e99ec.png)

@anushbhatia @smaranjitghose Assign this task to me?

**Comment by Kuljeet-123** [comment]
@smaranjitghose Can I work on this issue??
