### ISSUE TITLE
Optimize the content for SEO

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#34]
Find Words related to technical and girls who code.
Find traffic related to every word using any chrome extension.

**Comment by minolipvartak** [comment]
I'll do it. Please assign me this task

**Comment by paridhigulati** [comment]
Can I work on this, please? @anushbhatia

**Comment by minolipvartak** [comment]
hello, @anushbhatia. I have collected some well-paying keywords for the website. Please check it out. The numbers denote the Cost-per-click (CPC) in USD. 

The format is **{keyword - Avgerage search volume - CPC in USD}**

girls who code - 71700 - 2.12
girls can code - 700- 2.37
coding for kids	- 53300 - 1.48
coding camp for girls - 70 - 3.98
**how to code - 22600 - 2.16**
**girls who code program - 90 - 3.64**
**programmer girl - 1000 - 5.67**
engineering - 941000 - 1.66
technical - 177000 - 0.84
**technical college - 24300 - 6.56**
**tech events - 3400 - 3.18**
**coding competition - 4100- 2.04**
coding contest - 2500 - 1.22
**programming challenges - 5400 - 2.34**
**learn to code - 78300 - 6.65**
**learn programming - 18400 - 2.69**
coding competitions  for beginners  -  230 - 1.36
**programming - 13800 - 3**
**computer coding - 19300 - 4.75**
**programmer - 116000 - 2.04**
**computer programming - 836000 -  4.76**
**introduction to coding - 820 - 3.67**
**coding programs	- 4.12**
**learn computer programming - 2900 - 3.92**
introduction to programming - 4900 - 1.17
**learn programming - 18400 - 2.69**
simple computer program - 90 - 2.55
programming software - 14700 - 1.95
**computer coding for beginners - 660 - 3.43**

Do let me know if you need any additional keywords

**Comment by minolipvartak** [comment]
FYI, I am using the free trial of the KWFinder tool.

**Comment by anushbhatia** [comment]
https://stackoverflow.com/questions/3812143/how-many-keywords-are-ideal-for-the-meta-keywords-tag

Check through this and add keywords with Medium traffic. 

Put this code in keyword tag for html and post it here. 

One with high traffic for future use.

**Comment by minolipvartak** [comment]
For now, I have added 10 keywords to go safe with medium traffic. Is it good to go, @anushbhatia ?
```
<html>
<head>
<meta name="keywords" content="tech events, coding competition, introduction to coding, computer coding for beginners, girls who code program, coding contest, coding competition, girls can code, introduction to programming, learn computer programming">
</head>
</html>
```

**Comment by anushbhatia** [comment]
Cool make a pr and push it

**Comment by minolipvartak** [comment]
Done @anushbhatia. Please review it.

**Comment by minolipvartak** [comment]
Hello @anushbhatia. I have prepared a short intro by taking reference of the main website. This content contains the aforementioned keywords. Can you please review this content?

-------------------------------------------------------------------------------------------------------
GirlScript is a section-8 NON PROFIT company registered under the government of India on the 2nd June 2017. GirlScript host many **tech events** and **coding competition** to help you get started and **learn computer programming**. No matter whether you are a beginner or an experienced individual, GirlScript is open for all. 

GirlScript's mission is to encourage individuals to learn **how to code** and stand out among the crowd. Along with learning, GirlScript aims to create opportunities and growth via technical education among various groups of people. 

Goals:
1. Encourage people to learn to program and make them capable of writing a simple computer program to building a complex system. 
2. Empower people by providing an opportunity to showcase their **technical** skills.
3. Provide a platform to individuals by hosting **coding competition** and tech events. 
4. Share **technical** knowledge and content for helping individuals in the programming world.

**Comment by anushbhatia** [comment]
nice work now add this to the home page and if the content exceeds then add al ink for it separately.

**Comment by minolipvartak** [comment]
Yes. Thank you

**Comment by minolipvartak** [comment]
> 
> 
> nice work,
> now add this to the home page and if the content exceeds then add al ink for it separately.

Hello, I have added the Intro to the **About** section of the website, and made a PR for it. Can you please review it?

**Comment by minolipvartak** [comment]
Hey @anushbhatia. can you please share the analytics code for the SEO work?

**Comment by anushbhatia** [comment]
DM on slack what all u will require for it.

**Comment by anushbhatia** [comment]
till then have a description and og tags for SEO

**Comment by minolipvartak** [comment]
Hey @anushbhatia Can you please explain me in detail ? like which description? and og tags?

**Comment by anushbhatia** [comment]
go to [gssoc.tech](gssoc.tech) go to inspect element look through the top of the code u will get some information about it.

**Comment by minolipvartak** [comment]
hey @anushbhatia I have prepared a short desc according to SEO. Can you please review it? 

<meta name="description" content="GirlScript Chennai website is a base for Chennnai chapter, and serves a template for other chapters. All the channel-specific tech events, coding competitions, and other resources are mentioned in this website.">

**Comment by anushbhatia** [comment]
great add it.

**Comment by minolipvartak** [comment]
<meta name="application-name" content="GirlScript Foundation | Chennai Chapter">
<meta name="author" content="GirlScript Chennai">
<meta name="msapplication-tooltip" content="GirlScript Chennai is a website for the Chennai Chapter that showcases events and opportunities in Chennai.">
<meta name="apple-mobile-web-app-title" content="GirlScript Foundation | Chennai Chapter">
<meta name="og:site_name" content="{website_url}">
<meta name="og:title" content="GirlScript Foundation | Chennai Chapter">
<meta name="og:url" content="{website_url}">
<meta name="og:image" content="assets/Images/GirlScriptChennaiLogo.png">

**Comment by anushbhatia** [comment]
Go ahead
Give a pr

**Comment by abhu-A-J** [comment]
@anushbhatia Sir I'm interested as well. I want to start from index page

**Comment by minolipvartak** [comment]
Hello @anushbhatia is there anything else to be done for SEO?

**Comment by anushbhatia** [comment]
just google all SEO enhancement features in a website u will get a plenty of them.
