### ISSUE TITLE
Contact us changes

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#353]
**Description 
Captcha field is irrelevant. It is usually added in signup pages not in contact us

**Screenshots**
![Screenshot_2020-04-15-22-56-42-186_com android chrome](https://user-images.githubusercontent.com/31164665/79368149-9159d300-7f6c-11ea-9086-6a3064e90f2f.jpg)

@smaranjitghose can I work on it

**Comment by anushbhatia** [comment]
to stop bots from filling forms it is necessary
