### ISSUE TITLE
Announcement Page improvement

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#355]
**Description of the enhancement**
cards do not have proper css and it is looking improper . 
**Screenshots**
![Screenshot_2020-04-15-23-02-20-935_com android chrome](https://user-images.githubusercontent.com/31164665/79368659-5efca580-7f6d-11ea-8935-243dfef8a373.jpg)

@smaranjitghose can i work on this

**Comment by goyalmuskan** [comment]
@shreyakapoor08 I am working on it.
