### ISSUE TITLE
Conatct Us 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#36]
Improve the text fields use materialize ones and please try to improve the send message button.

**Comment by sonalsk** [comment]
We, team FemmeTech, would like to work on this issue. 
Please assign it to us.
@sakshi1499

**Comment by anushbhatia** [comment]
Please tell her to comment on this issue

**Comment by sonalsk** [comment]
We are working as a team for RGSoC, the mention was for the sake of team, sir.
You can assign the issue to me

**Comment by arpita-in** [comment]
issue #30  is same
