### ISSUE TITLE
Use of better fonts 

### ISSUE THREAD

**Issue by Kashish-max** [smaranjitghose/girlscript_chennai_website#363]
Upgradation of Font is needed on every page. As I'm learning Graphic designing I think I could do this job.

 Can I work on this issue?

**Comment by anushbhatia** [comment]
Drogowskaz
Futura
Selawik
Gotham
Montserrat
Source Sans Pro
Proximal nova
Poppins

**Comment by Kashish-max** [comment]
Sir these are suggestions or you want me to use fonts among these only?

**Comment by anushbhatia** [comment]
these are suggestions but if u want to give a new font just tell me the name before using it.

**Comment by Kashish-max** [comment]
ok

**Comment by YaminiShrestha31** [comment]
please assign me this
