### ISSUE TITLE
Contact Us Navbar Redirection Missing

### ISSUE THREAD

**Issue by sakshi1499** [smaranjitghose/girlscript_chennai_website#37]
Redirection in Contact Us navbar missing. Home and Contact Us navbar components give invalid results.

@sonalsk
![image](https://user-images.githubusercontent.com/42520146/76991920-6af64700-6970-11ea-9149-946d80aab5b7.png)

**Comment by sakshi1499** [comment]
We team femmetech would like to work on it @sonalsk

**Comment by anushbhatia** [comment]
Let her take it up voluntarily

**Comment by sakshi1499** [comment]
We are participating in RGSOC. Also, we are a team. @anushbhatia

**Comment by anushbhatia** [comment]
if she doesn't comment I can't assign it to her

**Comment by sakshi1499** [comment]
Assign it to me then 😊

**Comment by sakshi1499** [comment]
Also, I have already made a PR for the same @anushbhatia

**Comment by smaranjitghose** [comment]
@sakshi1499 Nice work!..Congrats on getting your first PR merged
