### ISSUE TITLE
Dark Mode Bugs

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#373]
![1587150230399](https://user-images.githubusercontent.com/40017559/79604831-732ad900-810c-11ea-817d-e84b9c0cf6c6.png)
Try solving this issue

**Comment by aashimgarg** [comment]
I am working on this @anushbhatia

**Comment by aashimgarg** [comment]
i added the darkMode for the index page only..

**Comment by Adyasha8105** [comment]
@anushbhatia Can I work on Team page ???

**Comment by aashimgarg** [comment]
I am on the pages.

**Comment by anushbhatia** [comment]
Distribute pages among urself

**Comment by Adyasha8105** [comment]
> Distribute pages among urself

Please reassign me as he wants to work on this himself only.
