### ISSUE TITLE
Announcement Page Bugs

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#379]
![Announcements - Google Chrome 18-04-2020 21_28_19](https://user-images.githubusercontent.com/40017559/79642540-ad06e880-81bb-11ea-869f-de92f9ee503f.png)
Spacing between Recent Events and upcoming events.

**Comment by shreyakapoor08** [comment]
can I do this @anushbhatia ?

**Comment by anushbhatia** [comment]
Go ahead
