### ISSUE TITLE
Edit Achievements Section in Home Page 

### ISSUE THREAD

**Issue by sonalsk** [smaranjitghose/girlscript_chennai_website#39]
Suggested changes : 
1. Change parting line and make it more responsive
2. Edit Information under Projects and Events
3. Make section responisve

@sakshi1499

![Screenshot from 2020-03-18 23-33-40](https://user-images.githubusercontent.com/51206050/76992320-17d0c400-6971-11ea-993d-6d5ca1f39cda.png)

**Comment by sonalsk** [comment]
We, team FemmeTech, would like to work on this issue.
Please assign it to us.
@sakshi1499

**Comment by anushbhatia** [comment]
Let her comment and take it voluntarily

**Comment by HariniJeyaraman** [comment]
@ousnik please assign this issue to me. Would like to contribute

**Comment by sakshi1499** [comment]
> Let her comment and take it voluntarily

We want to work on this issue as a team for RGSOC @anushbhatia

**Comment by goyalmuskan** [comment]
I am already working on it @anushbhatia under Homepage.

**Comment by anushbhatia** [comment]
let @goyalmuskan solve this issue if she isn't able to do it then I will assign it to @sakshi1499
