### ISSUE TITLE
Deleting all the Borders

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#391]
There should be a **border** on every page.

**Screenshot:**
![2020-04-19 (15)](https://user-images.githubusercontent.com/54095539/79692009-4f889f80-8280-11ea-8227-a6c54bf029c7.png)

**Comment by anushbhatia** [comment]
Remove borders from everywhere it doesn't look good

**Comment by Adyasha8105** [comment]
I have to remove borders from everywhere

**Comment by Samiksha99** [comment]
assign me this task
