### ISSUE TITLE
Blog section

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#4]
Embed blogs from https://medium.com/techequilla

**Comment by sharmakeshav10** [comment]
Please assign it to me @smaranjitghose and further guide me to proceed for the same.

**Comment by Sapna2001** [comment]
I would like to work on this. Please assign this to me.

**Comment by KHMohit** [comment]
I am interested in working on this issue, please assign me

**Comment by smaranjitghose** [comment]
medium.com/techequilla

**Comment by suchi12j** [comment]
I am interested to work on this

**Comment by shreoshi-roy** [comment]
@smaranjitghose please assign this issue to me, i am interested in working on this.

**Comment by HariniJeyaraman** [comment]
@smaranjitghose Please assign this issue to me

**Comment by FrozenGirl-spd** [comment]
@smaranjitghose  Can i work on this issue please?!!

**Comment by smaranjitghose** [comment]
@shreoshi-roy  You are assigned this for the next week.. Please makes sure there's no conflict with the home page while working

**Comment by roshankcjha** [comment]
Please assign me this issue to me @smaranjitghose .I am excited to work on this.

**Comment by shreoshi-roy** [comment]
I have already worked on this issue and working on a PR rn (just have to
fix alignment of a button)

**Comment by smaranjitghose** [comment]
@roshankcjha after @shreoshi-roy 's Pull Request, you can take over
