### ISSUE TITLE
Announcement Page cards

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#405]
**Description 
Content is touching the line
**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![Screenshot_2020-04-20-16-39-15-643_com android chrome](https://user-images.githubusercontent.com/31164665/79745278-9bd9eb00-8325-11ea-9d25-a2d31e96deff.jpg)

**Comment by shreyakapoor08** [comment]
Can I work on it

**Comment by anushbhatia** [comment]
Change the images too

**Comment by shreyakapoor08** [comment]
sure :)
