### ISSUE TITLE
Contact us page bug

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#406]
**Description of the enhancement**
Captcha overlapping the div
**Screenshots**
![Screenshot_2020-04-20-16-43-01-427_com android chrome](https://user-images.githubusercontent.com/31164665/79745694-6386dc80-8326-11ea-9989-4346e3c266b2.jpg)

**Comment by shreyakapoor08** [comment]
captcha overlapping the div

**Comment by Adyasha8105** [comment]
Can I do this part @anushbhatia ? as I was working on it?
