### ISSUE TITLE
Home Page correction

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#408]
**Description of the enhancement**
Content is not properly visible

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![image](https://user-images.githubusercontent.com/31164665/79746651-f70cdd00-8327-11ea-9ec6-ed8f6efdf889.png)

**Comment by shreyakapoor08** [comment]
can i work on it

**Comment by smaranjitghose** [comment]
Sure!
