### ISSUE TITLE
Footer bug

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#409]
**Description of the enhancement**
Some content is visible below the footer in contact us page

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![image](https://user-images.githubusercontent.com/31164665/79747115-c2e5ec00-8328-11ea-9f46-b448e497a7de.png)

**Comment by shreyakapoor08** [comment]
can I work on it

**Comment by smaranjitghose** [comment]
Try to put the toggle for dark mode on the side. It's taking up unnecessary space

**Comment by ashishnagpal2498** [comment]
This has been corrected in latest code.
