### ISSUE TITLE
Restyling FAQ

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#412]
*Screenshots of the proposed changes compared with the current version of the project
![image](https://user-images.githubusercontent.com/31164665/79746513-ba40e600-8327-11ea-9023-497d7d87d3b3.png)

**Comment by shreyakapoor08** [comment]
@anushbhatia Can i work on it

**Comment by YaminiShrestha31** [comment]
please assign this to me

**Comment by anurajbhandari5** [comment]
can you assign me?
