### ISSUE TITLE
Snowfall animation Home page

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#427]
**Description of the enhancement**
The snowfall animation on the home page "Our Achievements" section is a shifted upwards.

**Screenshots**
![Screenshot from 2020-04-20 21-35-35](https://user-images.githubusercontent.com/33172345/79775033-41568400-8351-11ea-8fa6-ff5846042667.png)

**Comment by Muskan-Mangal** [comment]
@smaranjitghose please assign this issue to me.

**Comment by Muskan-Mangal** [comment]
@anushbhatia @smaranjitghose sir, there isn't any snowfall animation in the local copy of this on my pc. Is the repo fully updated? 
![Screenshot from 2020-04-21 00-24-42](https://user-images.githubusercontent.com/33172345/79788794-d31cbc00-8366-11ea-8823-568ab8cf2f54.png)

**Comment by smaranjitghose** [comment]
![snow_fall](https://user-images.githubusercontent.com/46641503/79793337-06167e00-836e-11ea-9501-b578dba0924a.jpg)

- Make sure your local repo is at par with this upstream one.
- Also, since this website is hosted on netlify, check from the link in the README if required.
- the snow animation bug is the secondary, firstly the image in the background is split and needs to fixed .

**Comment by Muskan-Mangal** [comment]
yeah okay!

**Comment by smaranjitghose** [comment]
@Muskan-Mangal is this issue's work done?

**Comment by Muskan-Mangal** [comment]
I'm trying! I'll try to solve it till tomorrow more, if not done then u can unassign me. @smaranjitghose

**Comment by smaranjitghose** [comment]
Relax, take a couple of days more and try to contribute for this. Otherwise let me know.

**Comment by Muskan-Mangal** [comment]
@smaranjitghose where do u want this snowfall animation to display exactly?
In the whole black section 
![Screenshot from 2020-04-28 11-40-53](https://user-images.githubusercontent.com/33172345/80453176-5fba1200-8945-11ea-804c-1cc4d6593593.png)
or inside the our achievement container of this black section.
can u please high light the part so that i can adjust accordingly.
