### ISSUE TITLE
Transparency of welcome to block

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#428]
**Description of the enhancement**
The black box on the home page stating "welcome to..." is irrelevant. It would look much better if we increase it transparency.

**Screenshots**
![Screenshot from 2020-04-20 21-46-55](https://user-images.githubusercontent.com/33172345/79774738-d73ddf00-8350-11ea-891a-ef3333319b85.png)

**Comment by Muskan-Mangal** [comment]
@smaranjitghose  please assign it to me!

**Comment by anushbhatia** [comment]
before making a pr just message me on slack I will recommend you changes.
