### ISSUE TITLE
New Logo For footor

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#429]
**Description of the enhancement**
I want to make a new logo in Illustrator for the footer as the black text is not looking good.

**Screenshots**
![2020-04-20 (13)](https://user-images.githubusercontent.com/54095539/79775478-ee310100-8351-11ea-848d-19f445a2d3e9.png)

**Comment by smaranjitghose** [comment]
Sure!
