### ISSUE TITLE
Font color  related issue

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#435]
**Description of the enhancement**
because of the choosen color of font, what is written at the filp box isn't even visible properly in Join us section.
**Screenshots**
![Screenshot from 2020-04-21 00-49-06](https://user-images.githubusercontent.com/33172345/79791026-44aa3980-836a-11ea-8686-a51195d97309.png)

**Comment by Muskan-Mangal** [comment]
@anushbhatia assign this to me please.

**Comment by Kashish-max** [comment]
I am already working on this issue

**Comment by smaranjitghose** [comment]
It's resolved already.
You can do something if you wish:
- Change the content from AI,Machine Learning,Competitive Programming to:
       1. Internet of Things
       2. Machine Leaning
       3. Web Development
[Create 3 more below for]
       4. Cloud Computing
       5. Cyber security
       6. Robotics

The current images are quite monotonous and don't do justice to the content, make appropriate images for all of the above

**Comment by Muskan-Mangal** [comment]
@Kashish-max alryt!  No problem :)

**Comment by Muskan-Mangal** [comment]
@smaranjitghose  should I work on ur suggestion after opening it as an issue?
