### ISSUE TITLE
Dark Mode button

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#443]
![dark_mode button](https://user-images.githubusercontent.com/46641503/79807510-b5f8e500-8388-11ea-89bb-bf5d750e4af1.jpg)

- Remove the dark mode toggle button from footer and place it somewhere else.  Try to change to a new design for the button itself

**Comment by aashimgarg** [comment]
i want to work on this.

**Comment by Adyasha8105** [comment]
may I?
