### ISSUE TITLE
Dark Mode - Persist

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#446]
**Dark mode feature**
Once a user selects dark mode, it should persist throughout the project, until and unless the user changes it.

**Replicate**
1) Switch to dark mode.
2) Go to some other tab.

I would like to work on this issue.

**Comment by anushbhatia** [comment]
great Idea execute this well !!

**Comment by Dorson** [comment]
I had the same issue and coded a working solution.

Works with one and same CSS file + basic JavaScript functions for the switch and color settings memory recall on load.

Here is the GitHub Demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/


Feel free to copy, fork, adopt, port, etc...
