### ISSUE TITLE
Captcha Field Correction

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#447]
Captcha Field does not match with other input fields. 
![image](https://user-images.githubusercontent.com/36301481/79851298-bb831900-83e2-11ea-96f5-cbd890f6474e.png)

**Comment by Swadesh13** [comment]
Is this issue open for everyone ? Then I would like to work on it. 
![Contact Us - Google Chrome 22-04-2020 00_21_45 (2)](https://user-images.githubusercontent.com/59609488/79902962-ee073300-842f-11ea-9ed0-d7c18f4d9846.png)

**Comment by anushbhatia** [comment]
Center align the captcha

**Comment by aashimgarg** [comment]
> Is this issue open for everyone ? Then I would like to work on it.
> 
> Here, is the updated version:
> ![Contact Us - Google Chrome 22-04-2020 00_21_45 (2)](https://user-images.githubusercontent.com/59609488/79902962-ee073300-842f-11ea-9ed0-d7c18f4d9846.png)

pull the latest commit bro.

**Comment by ashishnagpal2498** [comment]
How come any1 is working on the issue ?
