### ISSUE TITLE
BUG: We create trends cards

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#459]
**Description of the enhancement**
In mobile while clicking on the cards it redirects to the top of the page instead of showing the text

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![image](https://user-images.githubusercontent.com/31164665/79893678-040df700-8422-11ea-8e3c-837fb955578d.png)

**Comment by Kashish-max** [comment]
Text appears on hover I guess this is because there is no hover effect in mobile

**Comment by shreyakapoor08** [comment]
yes @Kashish-max , that is happening because there is no hover effect so when you click on the card in mobile it redirects to the top of the page which should not happen. :)
