### ISSUE TITLE
Dark mode enhancement

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#468]
**Description of the enhancement**
I want to redesign the dark theme page by page.

**Comment by smaranjitghose** [comment]
@anushbhatia Wil guide you with this. 
Do it one page at a time!

**Comment by Adyasha8105** [comment]
> @anushbhatia Wil guide you with this.
> Do it one page at a time!

@smaranjitghose Okay, sir :)
