### ISSUE TITLE
BUG: with toggle button

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#474]
**Description of the enhancement**
When toggles to dark mode , the heading in black mixes with the background

**Before toggling**

![Screenshot from 2020-04-23 00-00-51](https://user-images.githubusercontent.com/33172345/80019709-8f0bf180-84f5-11ea-8fb2-14251adf1ed4.png)
**Dark mode**

![Screenshot from 2020-04-23 00-01-05](https://user-images.githubusercontent.com/33172345/80019767-a3e88500-84f5-11ea-8a4c-d1b14a891d96.png)

**Comment by Adyasha8105** [comment]
@Muskan-Mangal  I am already working on this #468 .

**Comment by anushbhatia** [comment]
wait for @Adyasha8105 to finish it

**Comment by Muskan-Mangal** [comment]
@Adyasha8105 np! keep working :)

**Comment by anushbhatia** [comment]
Do one thing align it little above because it's not centrally aligned if u can customize this.

**Comment by Muskan-Mangal** [comment]
okay I'll allign it! but why did u closed this issue. Is the toggle thing solved?

**Comment by anushbhatia** [comment]
https://codepen.io/_Raunaq_/pen/wbRwea
This is or reference but u can have something simple too.

**Comment by smaranjitghose** [comment]
@Muskan-Mangal  When you give the PR, try to make use of the above toggle button

**Comment by Adyasha8105** [comment]
> @Muskan-Mangal When you give the PR, try to make use of the above toggle button

@smaranjitghose I will work on it sir.

**Comment by Muskan-Mangal** [comment]
Yeah @Adyasha8105 and me are collaborating for this issue please assign it to her too.
