### ISSUE TITLE
Toggle problem in go to top button

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#480]
**Description of the enhancement**
On toggling to dark mode, goto top button style changes but it's not happening in our achievement template.
**Screenshots**
After toggling in achievement template
![Screenshot from 2020-04-23 13-01-01](https://user-images.githubusercontent.com/33172345/80072046-4e4ac180-8563-11ea-92c5-6ffffe732e27.png)

after toggling in other templates
![Screenshot from 2020-04-23 13-02-03](https://user-images.githubusercontent.com/33172345/80072053-50148500-8563-11ea-8b28-01192b4889c7.png)

**Comment by Muskan-Mangal** [comment]
@Adyasha8105  , since you are working on toggling issue, I think you will be the best choice to handle this issue too. Look into this matter.

**Comment by Adyasha8105** [comment]
> @Adyasha8105 , since you are working on toggling issue, I think you will be the best choice to handle this issue too. Look into this matter.

Okay sure @Muskan-Mangal .like I am working page by page.
