### ISSUE TITLE
Text color mathches with the background color

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#481]
**Description of the enhancement**
In Team template , text color and background color are almost a match.
It should be changed to white after toggling.

**Screenshots**
![Screenshot from 2020-04-23 13-09-20](https://user-images.githubusercontent.com/33172345/80072794-5eaf6c00-8564-11ea-9711-23a8a24104cc.png)

**Comment by Muskan-Mangal** [comment]
same problem exists in achievement template.
![Screenshot from 2020-04-23 13-20-18](https://user-images.githubusercontent.com/33172345/80073405-5c014680-8565-11ea-8e35-3a14af64b496.png)

**Comment by Muskan-Mangal** [comment]
> same problem exists in achievement template.
> ![Screenshot from 2020-04-23 13-20-18](https://user-images.githubusercontent.com/33172345/80073405-5c014680-8565-11ea-8e35-3a14af64b496.png)

this "projects by" should be white

**Comment by Adyasha8105** [comment]
@Muskan-Mangal I have already this issue.

**Comment by Muskan-Mangal** [comment]
@Adyasha8105 yeah , I thought to mention you since u were already working on dark mode toggling thing. But I already tagged u in one. That's great thay you have solved that :)
