### ISSUE TITLE
BUG : button not working

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#482]
**Description of the enhancement**
Button not working in articles of announcement template

**Screenshots**
This button
![Screenshot from 2020-04-23 13-24-27](https://user-images.githubusercontent.com/33172345/80073801-eb0e5e80-8565-11ea-855d-7200210b249e.png)

**Comment by anushbhatia** [comment]
Go ahead

**Comment by Adyasha8105** [comment]
@Muskan-Mangal I think this is not required now.

**Comment by Muskan-Mangal** [comment]
> @Muskan-Mangal I think this is not required now.

Yeah apparently not👍
