### ISSUE TITLE
font color and background

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#497]
**Description of the enhancement**
in announcement pages problem still persist. after toggling not properly readable text.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![Screenshot from 2020-04-24 00-39-34](https://user-images.githubusercontent.com/33172345/80139587-4f600b00-85c4-11ea-808c-68c7cfda4a63.png)

**Comment by Muskan-Mangal** [comment]
the border around dates should also become white after toggling

**Comment by Adyasha8105** [comment]
@Muskan-Mangal Like the changes happened recently so I have already changed it in my new PR.
