### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#5]
Update the home page in a home.html with relevant design corresponding to the rest of the website and add on the content

**Comment by smaranjitghose** [comment]
![gs_website_home_1](https://user-images.githubusercontent.com/46641503/76560217-b1f2c100-64c6-11ea-83e6-ad66784843c4.png)

- This website is for GirlScipt Chennai and not summer of code
- Make a logo for GirlScript Chennai
- Embed it properly with an appropriate background
- Change the Title
- Try to do something like this:  https://srmkzilla.net/ 
- For the content for a small demo fetch it from our LinkedIn and Twitter pages..And create your own if you wish..

**Comment by goyalmuskan** [comment]
May I work on this issue, since I am already enhancing the homepage?

**Comment by Yashank18** [comment]
Please assign me this issue, since I am already working along @goyalmuskan on the homepage!

**Comment by anushbhatia** [comment]
use better background, not a pixeled one
Make the cover responsive.
![1584551702272](https://user-images.githubusercontent.com/40017559/76988164-51520100-696a-11ea-9f7f-7087e7d90127.png)

**Comment by goyalmuskan** [comment]
Working on it @anushbhatia

**Comment by FrozenGirl-spd** [comment]
@smaranjitghose  Can i work on this issue please?!!

**Comment by anushbhatia** [comment]
check this issues @goyalmuskan 
![1584690263408](https://user-images.githubusercontent.com/40017559/77144780-c6c5ea80-6aac-11ea-8da1-24bbba1ab282.png)
![1584690259086](https://user-images.githubusercontent.com/40017559/77144783-c7f71780-6aac-11ea-827a-2f18b4a192df.png)
![1584690254736](https://user-images.githubusercontent.com/40017559/77144784-c88fae00-6aac-11ea-8915-1774d9113706.png)

**Comment by goyalmuskan** [comment]
On it @anushbhatia

**Comment by Yashank18** [comment]
@anushbhatia 
@goyalmuskan

I will do it

**Comment by goyalmuskan** [comment]
Sure @Yashank18

**Comment by anushbhatia** [comment]
guys please the responsiveness issue. If you are not able to we will assign it to somebody else.

**Comment by Yashank18** [comment]
I will do it today.
