### ISSUE TITLE
Remove carousel from home page to better alternative

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#502]
Add an SVG or any animation on that page instead of carousel.

**Comment by Adyasha8105** [comment]
Can I try?

**Comment by aashimgarg** [comment]
I want to work on this.

**Comment by anushbhatia** [comment]
you can use another carousel that's also ok but it should load faster

**Comment by smaranjitghose** [comment]
This issue is closed due to inactivity.
