### ISSUE TITLE
Announcement page correction

### ISSUE THREAD

**Issue by shreyakapoor08** [smaranjitghose/girlscript_chennai_website#511]
**Description of the enhancement**
Unwanted event cards and css improvement

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![image](https://user-images.githubusercontent.com/31164665/80227422-36f6fb80-866b-11ea-91f9-03253016f22c.png)

**Comment by anushbhatia** [comment]
Add links to the pages too
