### ISSUE TITLE
Remodification of team page

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#532]
I want to work on the design of the team page.
It is divided into three parts:-

- First I will redesign the whole team page adding various features mostly similar to the Gssoc team page and also make it responsive.
- I will add Github, Linkedin URL of every member.
- Next, I will work on the dark mode enhancement of that page.

@anushbhatia Please assign this task to me and I will want to do this work myself only.

**Comment by smaranjitghose** [comment]
@Adyasha8105 try to add some hover effects to the team page

**Comment by Adyasha8105** [comment]
@smaranjitghose as I have done all those required changes ... I am closing this issue.
