### ISSUE TITLE
Enahncement of Our INITIATIVES

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#536]
Enhancement of Initiatives section
![1587921855455](https://user-images.githubusercontent.com/40017559/80314746-ecaf7f00-8810-11ea-8887-2c3bb50969db.png)

**Comment by abhu-A-J** [comment]
Can I try? Also is there a design/mockup to follow?

**Comment by anushbhatia** [comment]
No, you can just make it more appealing

**Comment by smaranjitghose** [comment]
@
