### ISSUE TITLE
Improvement of Footer in Dark Mode

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#553]

**Comment by Adyasha8105** [comment]
Can I?

**Comment by Muskan-Mangal** [comment]
@Adyasha8105 issue #560  is also same I guess.. claim u r working on it already there too.

**Comment by Adyasha8105** [comment]
> @Adyasha8105 issue #560 is also same I guess.. claim u r working on it already there too.

Ya thanks :)
