### ISSUE TITLE
Documentation of the project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#554]
# __Exclusively use Sphinx for this__

We want a ```readthedocs``` format documentation website for this project. Check out the popular python packages like numpy,pandas,etc

The main page of the documentation should contain the details of the project,aim, and a list of contributors

Then Each section must tell anyone who has even no coding experience, which lines of code to change and where to put the assets to modify the website.

The goal of the project is to make a common template for making it easy for each and every chapter of GirlScript Foundation to setup their website within a few hours. So the documentation should serve the purpose to guide anyone doing this from start to end

# You are welcome to contribute if you have the following pre-requisites:
- Basics of Python
- Sphinx (Watch Pycon and PyData videos, it's easy to pick up)
- Markdown, Restructured Text
- HTML,CSS

# Sections :

- [x] Main page describing the project
- [ ] Detailed Table of Contents
- [ ] Contributors page section
- [x] Home page section
- [x] Contact Us page section
- [x] Team page section
- [x] Achievements page section
- [x] Announcements page section
- [x] Blog page section
- [ ] Dark Mode Switch and Suggestions
- [ ] License and Code of Conduct section
- [ ] Custom theme

 # Please give all PRs for this to the ```gh-pages``` branch

**Comment by Adyasha8105** [comment]
Can I?

**Comment by shreyakapoor08** [comment]
@smaranjitghose I will work on it individually. Let me know when to start :)

**Comment by smaranjitghose** [comment]
@shreyakapoor08 Definitely you can start off whenever you ready. But, the documentation would take time since we have to cover all of the pages so collaborate with @Adyasha8105 on this please.

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 Definitely you can start off whenever you ready. But, the documentation would take time since we have to cover all of the pages so collaborate with @Adyasha8105 on this please.

Got it 😊
@Adyasha8105 Can we connect over slack?

**Comment by smaranjitghose** [comment]
@shreyakapoor08 @Adyasha8105  Please give all PRs for this to the ```gh-pages``` branch

**Comment by smaranjitghose** [comment]
I guess the majority of home page is completed by now? So I am checking it off

**Comment by shreyakapoor08** [comment]
@smaranjitghose main page describing the project is also done, you can check that also 😊

**Comment by CipherGirl** [comment]
Hello mentor and assignees! I and my friend one of my friend @shadman-ahmed-chowdhury were looking for some issues for documentation in GSSoC, unfortunately, we couldn't find much. As this issue is already taken up. Just letting you know if there is some work to split up we'd love to join and work collaboratively!

**Comment by smaranjitghose** [comment]
@CipherGirl I have assigned both of you the corresponding issue for the GirlScript App project. For this project, once the first phase of the documentation is completed by @shreyakapoor08 and @Adyasha8105 , you are can contribute to enhance it.

**Comment by shreyakapoor08** [comment]
@smaranjitghose Announcement section is also complete @Adyasha8105. 😊
You can mark it check ✔️

**Comment by saloniankita** [comment]
Can I contribute individually to the Contact Us page section @smaranjitghose ?

**Comment by smaranjitghose** [comment]
> Can I contribute individually to the Contact Us page section @smaranjitghose ?

Pardon me, it was already assigned. Could you work on a custom css for the documenation. @anushbhatia will be able to guide you with this. Moreover, the position of the search bar and stuff needs some improvements, you can fix that too

**Comment by smaranjitghose** [comment]
@Adyasha8105 @shreyakapoor08  For this issue we should try to proceed as follows:
- For License ,Code of Conduct,Contributing Guidelines:just add them in them in the main page of documentation with a line or two for each. Also, a redirect to the files on the master branch of the repo

- For testing purposes, anyone of you just take out the required html,css files and the associated assets and push it to the docs folder on the master branch. 

- For hosting guide I would prefer to have a wiki on this repo rather than putting in the docs

- If you want to add other wikis, you can write on:
      - Deploying to Netlify (Detailed Process)
      - Using GitHub CLI (Not the Git bash we use)
      - SEO Tips (@anushbhatia is a resourceful person for this)
- The majority of the work to generate a v.0.0.1 for docs of this project is over. So two important things that we need to work on is:
       -  Improve the style of the documentation(there are blogs online or if you wish you can write a custom.css file)
        - Update the documentation as per changes in code every 3-5 days
