### ISSUE TITLE
darkMode :feat: (WAVE)

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#560]
**Description of the enhancement**
darkMode for the wave.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by Adyasha8105** [comment]
> **Description of the enhancement**
> darkMode for the wave.
> 
> **Screenshots**
> Screenshots of the proposed changes compared with the current version of the project

@aashimgarg I am working on this issue.
