### ISSUE TITLE
Footer Home page

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#570]
**Description of the enhancement**
The footer in light mode looks very cool but in dark mode it looks so odd.

**Screenshots**
In light mode the color of footer matches with the animation, so it is really looking great but
![Screenshot from 2020-04-28 10-45-20](https://user-images.githubusercontent.com/33172345/80449769-9855ed80-893d-11ea-8025-a0ce5a99642c.png)

see here, color of footer differs from that of animation, it should be gray to match so it really looks odd.
![Screenshot from 2020-04-28 10-45-31](https://user-images.githubusercontent.com/33172345/80449850-ccc9a980-893d-11ea-9078-2de5e2b9f640.png)

**Comment by Adyasha8105** [comment]
@Muskan-Mangal  Sir has already created an issue and I am working on it.

**Comment by Muskan-Mangal** [comment]
oh yeah okay! my bad :|
