### ISSUE TITLE
Background image looks odd

### ISSUE THREAD

**Issue by Muskan-Mangal** [smaranjitghose/girlscript_chennai_website#582]
**Description of the enhancement**
That doodle or image in the background looks so odd  in event1.html.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![Screenshot from 2020-04-28 19-35-05](https://user-images.githubusercontent.com/33172345/80498705-afbac800-8989-11ea-9c0f-bb5b4042fccf.png)

**Comment by Muskan-Mangal** [comment]
I won't be able to correct it. 
@anushbhatia @smaranjitghose please assign someone who volunteers

**Comment by aashimgarg** [comment]
i can work on it.

**Comment by Adyasha8105** [comment]
> i can work on it.

@aashimgarg I have done this image if you want to work on it then you can message me in slack

**Comment by Muskan-Mangal** [comment]
@Adyasha8105 I have no problem but I really suggest to claim the issue before working on that to acknowledge other contributors and save their time too.
Just a friendly suggestion :)

**Comment by Adyasha8105** [comment]
> @Adyasha8105 I have no problem but I really suggest to open the issue if not opened and claim the issue before working on that problem to acknowledge other contributors and save their time too.
> Just a friendly suggestion :)

Ya but if @aashimgarg wants to do this as he commented first.

**Comment by Adyasha8105** [comment]
@aashimgarg Are you working on this ???

**Comment by aashimgarg** [comment]
> @aashimgarg Are you working on this ???

yes.
