### ISSUE TITLE
Event Page bug

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#592]
**Description of the enhancement**
This image seems to be clumsy.
Either we should remove or put it on the left side (book image).
@anushbhatia What's your opinion sir?

**Screenshots**
![2020-04-29 (1)](https://user-images.githubusercontent.com/54095539/80568897-73cd4480-8a15-11ea-9253-ece9e5a69708.png)

**Comment by Muskan-Mangal** [comment]
issue #582 is same as this and @aashimgarg is assigned . Please check it once.

**Comment by Adyasha8105** [comment]
> issue #582 is same as this and @aashimgarg is assigned . Please check it once.

I am talking about the book image. His task is to change the boy image and I made an issue to either change or remove the book image as it looks very clumsy at first sight.

**Comment by Muskan-Mangal** [comment]
well I opened that issue for book image actually but it's okay may be you take it differently. 
No issues
@aashimgarg what are you working at that book image or or that boy image?
