### ISSUE TITLE
Achievements Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#6]

**Comment by himanshusharma89** [comment]
Hey @smaranjitghose , I would like to work on this issue. And can you add gssoc label to it also.

**Comment by smaranjitghose** [comment]
![Annotation 2020-03-14 230506](https://user-images.githubusercontent.com/46641503/76687344-08880880-6649-11ea-8001-77594068bd22.png)

The other pages are not at all visible from the Achievements page.Fix this

**Comment by smaranjitghose** [comment]
Follow the same basic theme as the home page

**Comment by smaranjitghose** [comment]
![Annotation 2020-03-14 230615](https://user-images.githubusercontent.com/46641503/76687370-3c632e00-6649-11ea-92cb-cd345d42f767.png)
 Remove this.

**Comment by smaranjitghose** [comment]
Again please make the page (footer) consistent with the Home page
![Annotation 2020-03-14 230640](https://user-images.githubusercontent.com/46641503/76687415-aed40e00-6649-11ea-9477-7c2e5e114608.png)

**Comment by smaranjitghose** [comment]
Have this in horizontal format
![gs2](https://user-images.githubusercontent.com/46641503/76687480-4c2f4200-664a-11ea-95e9-ea995af8fbe3.png)

**Comment by goyalmuskan** [comment]
May I work on this issue? @smaranjitghose

**Comment by shreoshi-roy** [comment]
@smaranjitghose please assign this issue to me, i am interested in working on this.

**Comment by atrip10** [comment]
Please Can i work on this issue?

**Comment by anushbhatia** [comment]
check this bug also and resolve it.
![1584551937866](https://user-images.githubusercontent.com/40017559/76988480-c1608700-696a-11ea-9ba7-f86fac5a8f9e.png)

**Comment by goyalmuskan** [comment]
@anushbhatia I have fixed it along with a few sections on that page, I will be creating a PR soon. :)

**Comment by mySTRiouscoder** [comment]
Hey! @smaranjitghose  I have some ideas to implement on this page. So, can you plz assign me as well ?

**Comment by anushbhatia** [comment]
![1585408597813](https://user-images.githubusercontent.com/40017559/77826450-6af70380-7135-11ea-8a4b-540d8f35356a.png)
increase the size of the logo
make the navbar the same as all pages
can you please make this page responsive too
![1585408772009](https://user-images.githubusercontent.com/40017559/77826470-aa255480-7135-11ea-9a65-a9d5920ef5a2.png)
please add colour to these.
 
divide the work @goyalmuskan and @mySTRiouscoder.

if someone else wants to contribute with them just message I will assign more work to you.

**Comment by anushbhatia** [comment]
increase the size of the logos

**Comment by mySTRiouscoder** [comment]
> increase the size of the logos

I made already as discussed on slack and gave a pull request but it was closed yesterday.

**Comment by smaranjitghose** [comment]
![achievments](https://user-images.githubusercontent.com/46641503/78349858-df142a00-75c1-11ea-8978-1ae78ce2905a.png)

Remove this part and add a section "See what our members are up to", let the cards be in a similar fashion

**Comment by goyalmuskan** [comment]
Sir, why was I unassigned this issue? @smaranjitghose

**Comment by smaranjitghose** [comment]
If you wish to work on this more, I can reassign you

**Comment by goyalmuskan** [comment]
Sure, I can work on the section you've asked to edit above.

**Comment by goyalmuskan** [comment]
> ![achievments](https://user-images.githubusercontent.com/46641503/78349858-df142a00-75c1-11ea-8978-1ae78ce2905a.png)
> 
> Remove this part and add a section "See what our members are up to", let the cards be in a similar fashion

this one

**Comment by goyalmuskan** [comment]
In the "See what our members are upto" section, I'll let the cards be the same, the data though, should I give social media icons in each card to view the member's profile on various platforms? @smaranjitghose

**Comment by smaranjitghose** [comment]
Ya let the cards be as its, no giving social media links is not required.
