### ISSUE TITLE
Cutomizable Optimization API addition 

### ISSUE THREAD

**Issue by abhu-A-J** [smaranjitghose/girlscript_chennai_website#600]
**Description of the enhancement**
 Introduce a Script which when attached to HTML documents will trigger out API calls to different optimization API and custom API (with watchers).

**What does it do?**
 It a custom JS file, which can be customized as per need to make some modern browser-based API calls, in the form of Navigation API, Timings API, Frame API, Server Timing API, Resource API and more and also give a chance to add watchers in between any service calls.

**How is it different from tools like Google  Lighthouse and network tab on chrome dev tool?**
- Since it's basically JavaScript code, it is highly customizable by adding watchers, which is not possible in any of these tools.
- It is even powerful enough to add watchers on the server that servers your static files and get those values on the client-side during development.
- One additional benefit is we can get all information about network activity as well on the console in the way we want.

**How do I propose to add**
To make it easier to watch values and timings print them on console with extra coloring to reading values better.

**How does it look**
 An example from one of the applications in which I had added it in the past (just a small part of it)
![Screenshot (177)](https://user-images.githubusercontent.com/49617450/80620153-3c858480-8a63-11ea-9338-9a74e163a2d1.png)

**What all I want to include for development purposes so others can utilize it**
- Navigation API
- Timings API
- Resource Timings API
- Performance Observers (these are custom watchers)
- Long Task API (most important on which tells you if you are blocking threads which possibly can slow down application)
- more improvements like lazy loading (highly effective), placeholder images to reduce first paint issue performace, caching ifrequired using browser based API's.

**Comment by anushbhatia** [comment]
this is done or anything more u want to add

**Comment by abhu-A-J** [comment]
> this is done or anything more u want to add

I am learning some more Sir, I'll close it soon if I am unable to add it or will inform you soon!

**Comment by abhu-A-J** [comment]
@anushbhatia Sir, you may close this issue! I don't think I have any new once to add until npm is used in the project! Thank you! You may reopen it if in future npm is added for some reason!
