### ISSUE TITLE
Enhancement of registration page

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#619]
I want to make the page more attractive.

**Comment by aashimgarg** [comment]
First let me finish working on the page @Adyasha8105 then you can proceed.

**Comment by Adyasha8105** [comment]
> First let me finish working on the page @Adyasha8105 then you can proceed.

@aashimgarg I have already started.

**Comment by aashimgarg** [comment]
> > First let me finish working on the page @Adyasha8105 then you can proceed.
> 
> @aashimgarg I have already started.

I was working on it from past two days!

**Comment by Adyasha8105** [comment]
> > > First let me finish working on the page @Adyasha8105 then you can proceed.
> > 
> > 
> > @aashimgarg I have already started.
> 
> I have been working on it for the last two days!

Okay then after your PR, I will start my work.
