### ISSUE TITLE
Back To Top button

### ISSUE THREAD

**Issue by mySTRiouscoder** [smaranjitghose/girlscript_chennai_website#62]
My idea is to add a back to top button using HTML,CSS and javascript too (probably)  which, upon clicked by the visitor will take him to the top of the page.

**Comment by minolipvartak** [comment]
@mySTRiouscoder I am willing to do this task.

**Comment by mySTRiouscoder** [comment]
@minolipvartak Even i'm a participant , created this issue myself. Sorry for the confusion.
