### ISSUE TITLE
Vendor support  and Validator

### ISSUE THREAD

**Issue by abhu-A-J** [smaranjitghose/girlscript_chennai_website#622]
A feature request
- Addition of web kits/ vendor prefixes on CSS along with validations from w3 to check correct syntax and markup to have uniform experience on all browsers! 

@anushbhatia Sir, if considered valid I would like to work on it alone to avoid confusion! Thank you!.

**Comment by anushbhatia** [comment]
Sure nobody will interfere in this

**Comment by abhu-A-J** [comment]
@anushbhatia Sir I am closing this since CSS was covered very nicely last time and not much has changed just a few lines only and people started adding it themselves as well so no work left here!
