### ISSUE TITLE
Making register form validate.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#623]
**Description of the enhancement**
Validating register form.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

related to #566

**Comment by Adyasha8105** [comment]
> **Description of the enhancement**
> Validating register form.
> 
> **Screenshots**
> Screenshots of the proposed changes compared with the current version of the project
> 
> related to #566

@aashimgarg Please wait for two days.
