### ISSUE TITLE
Enhancement in "Our Initiatives" Section

### ISSUE THREAD

**Issue by shwetagurnani** [smaranjitghose/girlscript_chennai_website#626]
**Description of the enhancement**
I think in "Our Initiatives" section the gap between 2nd and 3rd box is more as compared to between 1st 2nd and 3rd 4th. I want to fix this.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![Screenshot from 2020-05-02 01-20-57](https://user-images.githubusercontent.com/43384092/80837258-181cda00-8c14-11ea-87cd-0ccf5b2f22f3.png)

**Comment by abhu-A-J** [comment]
@shwetagurnani  since there is also one similar issue #536 , can you also link issue #536 in your PR so I see what you have worked on and avoid working on the same problem! Else we might overwrite each other's work unknowingly! 🤣  Thanks!

**Comment by shwetagurnani** [comment]
Sorry @abhu-A-J  I missed that issue. I'll link #536  in my PR to avoid any overwriting.Thanks for highlighting!
