### ISSUE TITLE
Letter spacing issue

### ISSUE THREAD

**Issue by pranesh6876** [smaranjitghose/girlscript_chennai_website#638]
![Screenshot (68)](https://user-images.githubusercontent.com/46838529/80871179-d69a3680-8cc8-11ea-8501-d31c4cb1d3d9.png)

**Comment by pranesh6876** [comment]
Hello @smaranjitghose sir, I found this spacing issue. Please assign me this issue if it is a valid issue.

**Comment by pranesh6876** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/46838529/80872213-29c2b800-8cce-11ea-82aa-36ce92ccaf9b.png)

**Comment by anushbhatia** [comment]
go ahead

**Comment by pranesh6876** [comment]
ok sir.

**Comment by pranesh6876** [comment]
sir @anushbhatia , Please review the PR #653 .
