### ISSUE TITLE
Enhancement: px-->rem unit for CSS Styling

### ISSUE THREAD

**Issue by abhu-A-J** [smaranjitghose/girlscript_chennai_website#65]
@smaranjitghose I can see that all the styles follow px units are their measure which isn't a good practise. I propose to refactor the codebase to work on rem units rather than px units.

Note: Since there still is a lot of work going on other components in order to avoid any conflicts I would like to keep the refactored code into a different stylesheet or as you say it.

**Comment by anushbhatia** [comment]
No need for this
