### ISSUE TITLE
Back End for registration Form

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#650]
**Description of the enhancement**
I want to change the theme of the registration page like other pages.

**Comment by anushbhatia** [comment]
what all changes you want to make

**Comment by Adyasha8105** [comment]
> what all changes you want to make

sorry, mistakenly I have written contact form. @anushbhatia

**Comment by aashimgarg** [comment]
if at all you wanted to change the background theme then why you changed the image! changing then again changing?

**Comment by Adyasha8105** [comment]
> if at all you wanted to change the background theme then why you changed the image! changing then again changing?

theme means like the other pages not the color.

**Comment by aashimgarg** [comment]
Please elaborate what does backEnd include @anushbhatia.

**Comment by anushbhatia** [comment]
yes, connect it to a firebase account and prevent null values

**Comment by Adyasha8105** [comment]
@aashimgarg Do you want to do this as I am new to backend :(?

**Comment by Adyasha8105** [comment]
@aashimgarg If you want to work on this then you can take it :)

**Comment by smaranjitghose** [comment]
The remaining work will be done with the backend specific issues
