### ISSUE TITLE
Enhancement of confetti in Achievements 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#651]
I wanted to have something like [Link](https://twitter.com/i/status/1000968725158244352)
![1588491445573](https://user-images.githubusercontent.com/40017559/80908675-72ff2000-8d3f-11ea-9d1b-4a8420b150f9.png)

**Comment by aashimgarg** [comment]
I want to work on it.

**Comment by shwetagurnani** [comment]
I want to work on this.I am new to this project.Please assign me

**Comment by aashimgarg** [comment]
> I want to work on this.I am new to this project.Please assign me

i have been working on it.

**Comment by shwetagurnani** [comment]
@aashimgarg It is not yet assigned to you. That's why I asked the mentor to assign me. Moreover, let the mentor decide who will work:)

**Comment by anushbhatia** [comment]
both of you can work on it I have two tasks so 
1. make this achievement @aashimgarg 
2. On click of register button have a confetti @shwetagurnani 
[Refrences for second one](https://codepen.io/orrybaram/pen/LxOMwG)

**Comment by anushbhatia** [comment]
@shwetagurnani any Update

**Comment by abhu-A-J** [comment]
@anushbhatia @smaranjitghose can I do the confetti work for the second point if it's free?

**Comment by abhu-A-J** [comment]
@anushbhatia Can I work on the second confetti part?
