### ISSUE TITLE
Enhancement of registration form

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#652]
[Link to the page](https://girlscriptboilerplate.netlify.app/registrations)

1. Add header and footer
2. Add Vectors 
**Any more enhancements will be welcome.**

**Comment by aashimgarg** [comment]
I want to work on it.

**Comment by Adyasha8105** [comment]
> [Link to the page](https://girlscriptboilerplate.netlify.app/registrations)
> 
> 1. Add header and footer
> 2. Add Vectors
>    **Any more enhancements will be welcome.**

actually i have already mage an issue for it.

**Comment by aashimgarg** [comment]
> > [Link to the page](https://girlscriptboilerplate.netlify.app/registrations)
> > 
> > 1. Add header and footer
> > 2. Add Vectors
> >    **Any more enhancements will be welcome.**
> 
> Actually I have already made an issue for it.
> @anushbhatia Please assign the issue to me in my issue.

its closed!

**Comment by Adyasha8105** [comment]
> > > [Link to the page](https://girlscriptboilerplate.netlify.app/registrations)
> > > 
> > > 1. Add header and footer
> > > 2. Add Vectors
> > >    **Any more enhancements will be welcome.**
> > 
> > 
> > Actually I have already made an issue for it.
> > @anushbhatia Please assign the issue to me in my issue.
> 
> its closed!

no not at all

**Comment by anushbhatia** [comment]
Both of you can do it which page looks better that will be merged @Adyasha8105 @aashimgarg
