### ISSUE TITLE
Bug Achievement

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#658]
**Bug** 
The last card of achievement page is abrupt.
![image](https://user-images.githubusercontent.com/36301481/80912130-781c9900-8d58-11ea-9535-28f367c5a9de.png)
Also when we open a card, and scroll to top button visible, it changes to chevron down.
![image](https://user-images.githubusercontent.com/36301481/80912158-adc18200-8d58-11ea-8fc9-811a43cc59a6.png)

**Comment by anushbhatia** [comment]
Any Updates?

**Comment by ashishnagpal2498** [comment]
Yes , I am working on it. 
Found one more issue, 
If the card in more Div is open and user clicks on show Less, the UI remains disabled.
1) 
![image](https://user-images.githubusercontent.com/36301481/81060707-a0d79680-8ef0-11ea-93df-ad6a1d01d0f5.png)

![image](https://user-images.githubusercontent.com/36301481/81060729-ac2ac200-8ef0-11ea-8d41-0ed2c550f54d.png)

Doing this in same PR.
