### ISSUE TITLE
Better error display Contact Us

### ISSUE THREAD

**Issue by ashishnagpal2498** [smaranjitghose/girlscript_chennai_website#659]
Currently if the field is empty or wrong value entered, alert box is shown.
The current feature can be changed t error message placed about the fields with focus on those fields.
![image](https://user-images.githubusercontent.com/36301481/80912241-36402280-8d59-11ea-880c-824f14f74750.png)

**Comment by aashimgarg** [comment]
> Currently if the field is empty or wrong value entered, alert box is shown.
> The current feature can be changed t error message placed about the fields with focus on those fields.
> ![image](https://user-images.githubusercontent.com/36301481/80912241-36402280-8d59-11ea-880c-824f14f74750.png)

hey by the way i corrected that in my PR.

**Comment by anushbhatia** [comment]
add a helper text below it
