### ISSUE TITLE
Modify Dark Mode switch to day/night themed switch

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#663]
Refer:

https://codepen.io/jsndks/pen/qEXzOQ

**Comment by Adyasha8105** [comment]
I want to work on this

**Comment by ashishnagpal2498** [comment]
Can I work on this issue?

**Comment by anushbhatia** [comment]
[https://codepen.io/haxzie/pen/xxKNEGM](https://codepen.io/haxzie/pen/xxKNEGM)
Refer this too!!

**Comment by smaranjitghose** [comment]
@ashishnagpal2498  you can start working on this according to the one I suggested, however give a PR only after @Adyasha8105 's is merged so that there no conflicts
