### ISSUE TITLE
Fixing HTML validator errors

### ISSUE THREAD

**Issue by Castella1313** [smaranjitghose/girlscript_chennai_website#666]
Description 
Aims to resolve all HTML validation issues associated with HTML files.

**Comment by anushbhatia** [comment]
Which issue specifically can you share the screenshot

**Comment by Castella1313** [comment]
**w3c validator is showing these errors in the file achievements.html**


![Screenshot 2020-05-04 at 1 00 26 PM](https://user-images.githubusercontent.com/53293156/80944674-bcb33d80-8e07-11ea-9a1d-7860850daaae.png)


![Screenshot 2020-05-04 at 1 00 40 PM](https://user-images.githubusercontent.com/53293156/80944677-be7d0100-8e07-11ea-94ff-1b127222f670.png)


![Screenshot 2020-05-04 at 1 00 54 PM](https://user-images.githubusercontent.com/53293156/80944682-bfae2e00-8e07-11ea-98aa-727bea99283a.png)

**Comment by anushbhatia** [comment]
Go ahead with it

**Comment by Castella1313** [comment]
@anushbhatia @aman-atg may you please review my PR !!!

**Comment by abhu-A-J** [comment]
@anushbhatia Sir  @Castella1313 Open to collaboration? If yes, I would like to chip in as well. Else you may continue

**Comment by Castella1313** [comment]
@abhu-A-J yup, its absolutely fine. I have no problem with this.

**Comment by Castella1313** [comment]
@abhu-A-J let me know which file you will be working at?

**Comment by abhu-A-J** [comment]
> @abhu-A-J let me know which file you will be working at?

Hey! I was thinking on the team, contact and achievements.
But it's upto you, you can tell me which ones I can take since you created the issue!

**Comment by Castella1313** [comment]
@abhu-A-J achievements.html is already done. you can take up the rest two.

**Comment by anushbhatia** [comment]
do it for home page too
