### ISSUE TITLE
:feat: scrollIndiacator for the page.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#673]
**Description of the enhancement**
By adding this user will know when the page is going to end.

**Comment by anushbhatia** [comment]
which colour?

**Comment by aashimgarg** [comment]
> which colour?

any shade of black!

**Comment by anushbhatia** [comment]
we can have this in blog page

**Comment by aashimgarg** [comment]
> we can have this in blog page

in the index page too

**Comment by anushbhatia** [comment]
it will look weird in dark mode

**Comment by aashimgarg** [comment]
> it will look weird in dark mode

we can change the color in the darkMode

**Comment by anushbhatia** [comment]
which colour?

**Comment by aashimgarg** [comment]
> which colour?

white or orange  which ever will suit more!

**Comment by anushbhatia** [comment]
Will that not make the navbar look big?

**Comment by aashimgarg** [comment]
> Will that not make the navbar look big?

i dont think so.... because its a very thin line.

**Comment by anushbhatia** [comment]
if this looks good then we will keep it else remove it

**Comment by aashimgarg** [comment]
> if this looks good then we will keep it else remove it

cool!!
