### ISSUE TITLE
change the description in every page

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/girlscript_chennai_website#680]
**Description of the enhancement**
I want to change this part on every page according to girl script boilerplate.

**Screenshots**
![2020-05-05 (3)](https://user-images.githubusercontent.com/54095539/81036763-e9299100-8ebd-11ea-92f3-4f741db24aca.png)

**Comment by anushbhatia** [comment]
@abhu-A-J is already working on this
