### ISSUE TITLE
adding double diagonal section separators instead of Parallax.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#685]
**Description of the enhancement**
adding double diagonal section separators instead of Parallax.

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by anushbhatia** [comment]
where exactly

**Comment by aashimgarg** [comment]
> where exactly

like the index page which has parallax so instead of that we can have doublediagonal section seperators.
