### ISSUE TITLE
Enhancement in home page

### ISSUE THREAD

**Issue by shwetagurnani** [smaranjitghose/girlscript_chennai_website#689]
**Description of the enhancement**
In Our Initiatives Section-I want to add box-shadow (orangish) and make the borders and increase the corner radius

In WE CREATE TRENDS FOR THE WORLD Section: I want to change the box-shadow to orangish. Also, the image for Internet of things is not being loaded

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
![Screenshot from 2020-05-06 01-17-50](https://user-images.githubusercontent.com/43384092/81109919-78738a80-8f38-11ea-9bd0-018c5eea9803.png)
![Screenshot from 2020-05-06 01-28-43](https://user-images.githubusercontent.com/43384092/81110322-051e4880-8f39-11ea-83c7-c2efa77a9fd1.png)

**Comment by Adyasha8105** [comment]
> the image for Internet of things is not being loaded

The image for the Internet of things is not being loaded. Are u sure?

**Comment by smaranjitghose** [comment]
@shwetagurnani for the current version of the code base, this is working fine
