### ISSUE TITLE
Team Page (Enhancement)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#690]
- [x] Change the UI to Add Parallex Depth to the cards for each member
Refer [this](https://codepen.io/andymerskin/full/XNMWvQ)
- [x] Each member should have options to include Linkedin,GitHub
- [ ] Team Division: Board, Technical Team, Marketing Team, Creatives Team,Publicity Team

__For any Pull Request you give, including relevant comments is mandatory for review__

**Comment by Adyasha8105** [comment]
@smaranjitghose As I made the team page, I want to work on this.

**Comment by Adyasha8105** [comment]
I want to work on the first task @smaranjitghose

**Comment by abhishekgupta368** [comment]
Assign me

**Comment by aashimgarg** [comment]
I will work on the third one then.

**Comment by smaranjitghose** [comment]
@abhishekgupta368 you are assigned #1 and #2 for the next 5 days. If you need help with the design have a talk with @anushbhatia or let me know on slack

**Comment by smaranjitghose** [comment]
Any updates @abhishekgupta368 ?

**Comment by Adyasha8105** [comment]
@Adyasha8105 Sir today I will do this work. Sorry for being late.

**Comment by Kashish-max** [comment]
Can I work on this issue?

**Comment by smaranjitghose** [comment]
> Can I work on this issue?

Let @abhishekgupta368 spend a day or two for contributing to this. Otherwise, tag me again here, I'll assign it to you

# Note:

- I have given a preferable style and transition for the cards above. You can surely modify it as suited.
- For the guidance related to design, please contact @anushbhatia if it is need
- We are using JSON for entering the data as done by @abhu-A-J [here](https://github.com/smaranjitghose/girlscript_chennai_website/pull/781). So please make sure, you follow the same
-  Finish off with the simple cards, with names of the members and on hover showing the team
- After that work on integrating links to social media profiles

**Comment by abhishekgupta368** [comment]
I will do it?

**Comment by sanchibansal340** [comment]
@smaranjitghose Can I work on the third part of this issue?

**Comment by anushbhatia** [comment]
@abhu-A-J is working on this you can ask him once and you can work together

**Comment by anushbhatia** [comment]
- [ ] Team Division: Board, Technical Team, Marketing Team, Creatives Team, Publicity Team
- [ ] Remove border around the cards
- [ ] Add a set of 3 or 4 Cards in a row 
- [ ] Dark mode fo the website

**Comment by Adyasha8105** [comment]
Can I work on this issues?

**Comment by aashimgarg** [comment]
> * [ ]  Team Division: Board, Technical Team, Marketing Team, Creatives Team, Publicity Team
> * [ ]  Remove border around the cards
> * [ ]  Add a set of 3 or 4 Cards in a row
> * [ ]  Dark mode fo the website

like @anushbhatia I didn't get about the darkMode. we have it🤔

**Comment by Adyasha8105** [comment]
dark mode of team page.

> > * [ ]   Team Division: Board, Technical Team, Marketing Team, Creatives Team, Publicity Team
> > * [ ]   Remove border around the cards
> > * [ ]   Add a set of 3 or 4 Cards in a row
> > * [ ]   Dark mode fo the website
> 
> like @anushbhatia I didn't get about the darkMode. we have it🤔

Dark mode of team page

**Comment by anushbhatia** [comment]
That section needs is revamped so the dark mode features will change accordingly
