### ISSUE TITLE
Dark Mode Switch [Enhancement]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#691]
- [ ] Improve the design of the dark mode switch
- Preferable look : https://codepen.io/jsndks/pen/qEXzOQ
- [ ] __Don't use any external assets. You are expected to design it from scratch__

**Comment by Adyasha8105** [comment]
@smaranjitghose I will do the exact same thing in this link :).

**Comment by aashimgarg** [comment]
i can work on this.

**Comment by ashishnagpal2498** [comment]
I think I was suppose to be working on this, according to #663 @smaranjitghose ?

**Comment by smaranjitghose** [comment]
I guess @anushbhatia had closed that one, and further I didn't see any from your side regarding this after the first enhancement was merged,hence I raised a new issue.

**Comment by smaranjitghose** [comment]
Do you want to work on this one?

**Comment by ashishnagpal2498** [comment]
Yeah sure.

**Comment by smaranjitghose** [comment]
> Yeah sure.

Let @aashimgarg make his contribution for the next 2 days, after that you can improve upon it

**Comment by smaranjitghose** [comment]
@ashishnagpal2498 You are assigned the work for the next 4 days
