### ISSUE TITLE
Home Page [Enhancement]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#692]
- [ ] The text current animation loads twice for the first string.  Apply a different effect

**Comment by Adyasha8105** [comment]
> * [ ]  The text current animation loads twice for the first string.  Apply a different effect

Ya as I have made this effect. I will solve the bug.

**Comment by smaranjitghose** [comment]
> > * [ ]  The text current animation loads twice for the first string.  Apply a different effect
> 
> Ya as I have made this effect. I will solve the bug.

Experiment with some other effects as well
