### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#7]
Create a Team Page with animations like this:
https://dscvit.com/team.html

**Comment by payal-98** [comment]
what we have to do in this @smaranjitghose ?

**Comment by smaranjitghose** [comment]
Create a Team Page with animations like this:
https://dscvit.com/team.html

**Comment by Sapna2001** [comment]
@smaranjitghose can I work on this?

**Comment by SaranshDawra** [comment]
@smaranjitghose I would like to work on this issue. Please assign me with this issue.

**Comment by manan-bedi2908** [comment]
May I work on this
?

**Comment by payal-98** [comment]
@smaranjitghose Okk I will do....Please assign me this issue

**Comment by smaranjitghose** [comment]
Assigned to @payal-98 for the next 5 days..post that @SaranshDawra can take over

**Comment by shreoshi-roy** [comment]
@smaranjitghose please assign this issue to me, i am interested in working on this.

**Comment by FrozenGirl-spd** [comment]
@smaranjitghose  can i work on this issue?
