### ISSUE TITLE
Redesigning footer

### ISSUE THREAD

**Issue by Mustafiz04** [smaranjitghose/girlscript_chennai_website#70]
- Resize the footer size. Fix the logo size and add a link to the top.
- Proper alignment of join our newsletter, email form and send button.
- Aligning the send button alongside the email form for the dense look.
- Fix the social media icon with proper color and hover effect. 

I would like to work on this issue please assign to me under GSSoC'20.

![1](https://user-images.githubusercontent.com/49086821/77288655-4bf40e00-6cfe-11ea-9206-826276e5affa.png)

**Comment by shubhammantri1** [comment]
I want to work on this issue. Please assign it to me. @Mustafiz04

**Comment by anushbhatia** [comment]
If @Mustafiz04 doesn't finish in 3 days I will assign this to you.
