### ISSUE TITLE
Responsiveness Issue 

### ISSUE THREAD

**Issue by abhu-A-J** [smaranjitghose/girlscript_chennai_website#71]
**Describe the bug**
The section which shows the `WE CREATE TRENDS FOR THE WORLD` and it's image circular component aren't responsive. The spacing gets messed up on going small screens along with the incorrect alignment of the circular components.

The part when it's starting to align correctly, the spacing gets destroyed.

Anything under 400px width the circular images deform and continue's till all smaller screens.

**Expected behavior**
Should be properly centered at the page along with size should reduce down so it doesn't distort out!

**Screenshots**
Screenshots to help explain theproblem.

![GirlScript _ Chennai](https://user-images.githubusercontent.com/49617450/77297049-bdd45380-6d0e-11ea-84b5-a6178d21a16b.gif)

**Additional context**
If it's a concerning issue I'll like to try and fix the issue keeping in the same style's.

**Comment by anushbhatia** [comment]
actually people are already working on it #5
