### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#72]
Create a page like the one uploaded
![Events](https://user-images.githubusercontent.com/40017559/77303335-ce89c700-6d18-11ea-8e41-cff0b59f5f66.png)

You can play with colours

**Comment by abhu-A-J** [comment]
i'm interested in doing this

**Comment by Aman-Codes** [comment]
@smaranjitghose @anushbhatia I am a GSSOC participant and I would love to work on this. Please assign me this issue.
