### ISSUE TITLE
Custom Loader 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#720]
[https://codepen.io/CrocoDillon/details/Htycs](https://codepen.io/CrocoDillon/details/Htycs)
Something kind of this for the complete website
but it should be light

**Comment by aashimgarg** [comment]
It should be present in the initial phase of loading right?

**Comment by anushbhatia** [comment]
yes

**Comment by abhu-A-J** [comment]
May I also try it Sir with custom-designed SVG's ??

**Comment by anushbhatia** [comment]
yes sure
