### ISSUE TITLE
Dark Mode Color Scheme 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#732]
**Follow the XD file provided and take the colour codes from there and use it.**

Apply this scheme on the home page
Use of minimal orange colour in the project
Follow the mockup given below these are just samples:

**background** 121212
**card** 1e1e1e
**font light** a2a2a2
**highlight font** dfdfdf
**Main heading** dddddd

[Figma Document](https://www.figma.com/file/cr1E8OpdsptoC5rjf6nmTm/Material-Dark-Theme-Design-Kit?node-id=0%3A13)
[XD/Sketch File](https://drive.google.com/drive/folders/1i0bQvxmai8v25IV1GrOxCCsd5rLQNgzo?usp=sharing)

**For any issues contact the mentors**

**Comment by Adyasha8105** [comment]
Actually I have already taken up 1-2 issues. If possible, I want to work on this issue too.

**Comment by anushbhatia** [comment]
Finish the previous issues then you can surely work on this one.

**Comment by Adyasha8105** [comment]
Now I can work on it :)
