### ISSUE TITLE
adding fat arrows in place of normal JS functions.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#736]
**Description of the enhancement**
Replacing the current functions with the fat arrows syntax.
It’s much shorter!
We are able to omit the curly braces and the return statement due to implicit returns 

Its fast too.
**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by aashimgarg** [comment]
@anushbhatia what are your views?

**Comment by anushbhatia** [comment]
I will reopen it after all the issues are done
