### ISSUE TITLE
Dynamic Card Injection

### ISSUE THREAD

**Issue by abhu-A-J** [smaranjitghose/girlscript_chennai_website#744]
Dynamic Injection of Cards on Team and Achievements and others
 
Eg: The team page has over 15 cards which can increase or decrease with time.
Maintaining the cards (editing details, addition, and deletion of information from HTML, etc )  will become very difficult with time.
I want to insert them dynamically by converting the details to JS Objects with data.

This goes a long way in the future since maintaining it becomes very easy.

@anushbhatia Sir @smaranjitghose  Sir, kindly assign me the work if you think it's valid!
Also, I would like to work on it alone to avoid conflicts and confusion.

**Comment by abhu-A-J** [comment]
@smaranjitghose Sir, I am almost done with injecting all cards only two more are left.
I wanted to ask after completing them should I moduralized everything which means I'll keep one file named ` cardDesigns.js` where call card components will be present and one `dataFile.js` and export  these files! 
And that way I can clean up code in parent files by importing the required files! instead of having them all in one file (which is currently the case)

**Comment by smaranjitghose** [comment]
@Adyasha8105 @shreyakapoor08 Please update the documentation as per this
