### ISSUE TITLE
Returning Boolen values from JS functions.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#752]
**Description of the enhancement**
Many of the JS functions are used only for the if else purposes.
But,  all the **comparison operators** return boolean values. So we can replace the if-else statements with the simple return value. I think this will be very useful.

This will minimise and enhance the code a lot.

@anushbhatia what are your thoughts?

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by aashimgarg** [comment]
@anushbhatia what are your thoughts?

**Comment by anushbhatia** [comment]
ok but it should decrease the lines of code okay?

**Comment by aashimgarg** [comment]
> ok but it should decrease the lines of code okay?

yes for sure!!!
