### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#794]
Any bugs coming up in project should be mentioned here and the person will be assigned to resolve it.
You can also help or assist the person already working on an issue by mentioning the error here.

**Comment by aashimgarg** [comment]
Using let keywords instead of var to avoid duplication. @anushbhatia .

**Comment by anushbhatia** [comment]
Okay you can do that

**Comment by Adyasha8105** [comment]
@anushbhatia I want to work on the persist state of dark mode.

**Comment by anushbhatia** [comment]
okay go ahead

**Comment by Adyasha8105** [comment]
another bug
![2020-05-18 (7)](https://user-images.githubusercontent.com/54095539/82197250-5e628080-9918-11ea-8a7c-15fb62e1f1da.png)

**Comment by Adyasha8105** [comment]
I am working on the team page enhancement and the dark mode :)

**Comment by Adyasha8105** [comment]
Working on the footer bug :)

**Comment by anushbhatia** [comment]
What's the bug?

**Comment by Muskan-Mangal** [comment]
@anushbhatia no scroll to top functionality in event1.html template

**Comment by anushbhatia** [comment]
**For Registartion Page**
- [ ] Validate Registration no. 
Format
RA1711003010645 
RA1611008010002
- [ ] Custom Error message in the form of toast 
- [ ] Resolve errors in console
- [ ] Year of study not greater than 5

**Comment by Adyasha8105** [comment]
I will gonna work on this sir. @anushbhatia

**Comment by aashimgarg** [comment]
> **For Registartion Page**
> 
>     * [ ]  Validate Registration no.
>       Format
>       RA1711003010645
>       RA1611008010002
> 
>     * [ ]  Custom Error message in the form of toast
> 
>     * [ ]  Resolve errors in console
> 
>     * [ ]  Year of study not greater than 5

can i go for it?

**Comment by anushbhatia** [comment]
@Adyasha8105 is given today's time if she is able to do it otherwise I will give it to u @aashimgarg

**Comment by aashimgarg** [comment]
> @Adyasha8105 is given today's time if she is able to do it otherwise I will give it to u @aashimgarg

working on this!

**Comment by Adyasha8105** [comment]
its only 4 hours and sir haven't unassigned me. I am still working on it.

**Comment by aashimgarg** [comment]
@Adyasha8105 i was working on the other two!
