### ISSUE TITLE
Announcements Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_chennai_website#8]

**Comment by atrip10** [comment]
I would like to work on this issue

**Comment by shreoshi-roy** [comment]
@smaranjitghose please assign this issue to me, i am interested in working on this.

**Comment by smaranjitghose** [comment]
Collaborate with @atrip10 and give concurrent PRs

**Comment by Mustafiz04** [comment]
Why this issue is still open??

**Comment by smaranjitghose** [comment]
This is because there are design improvements the mentors are planning to inculcate

**Comment by smaranjitghose** [comment]
![announcments](https://user-images.githubusercontent.com/46641503/78424126-ef430c80-7688-11ea-8c5f-e9fdd1321477.png)

Fix this

**Comment by smaranjitghose** [comment]
![announcments_2](https://user-images.githubusercontent.com/46641503/78424344-8361a380-768a-11ea-843a-f770cf977125.png)

Make sure its aligned with the border
