### ISSUE TITLE
chore: adding the eslint plugin for React hooks.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_chennai_website#838]
**Description of the enhancement**
A clear and concise description of what the problem you wish to solve or any enhancement you wish to do for the project

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by anushbhatia** [comment]
why not JSLint or JSHint?

**Comment by aashimgarg** [comment]
> why not JSLint or JSHint?

![Screenshot from 2020-05-19 18-11-46](https://user-images.githubusercontent.com/55639487/82327940-cbe7dd00-99fc-11ea-91ce-6663033a2a88.png)

as we already using the esLint in the dependencies.
