### ISSUE TITLE
Adding linters and other good supports in the form of npm

### ISSUE THREAD

**Issue by abhu-A-J** [smaranjitghose/girlscript_chennai_website#893]
**Description of the enhancement**
Now that project is about to be over I think it will be good to add linting support and other few npm packages to the project to improve what everyone has worked on since last 3 months

**Screenshots**
Not valid

**Example**
- ES Lint an it's plugins
- scripts to start live server for development (to see changes without refreshing)
- making prettier bound to project by adding it's npm package
- scripts to minify, compress, etc

@anushbhatia Sir will it be okay? Also, do you have anything in mind to add?

**Comment by aashimgarg** [comment]
@abhu-A-J i can work too!

**Comment by abhu-A-J** [comment]
> @abhu-A-J i can work too!

Sure bro! We can split work if it gets approved! I will contact you on slack to discuss the same

**Comment by aashimgarg** [comment]
i was reading about the plugins and found eslint-plugin-jsx-a11y to be one of the useful plugins as it will help fix common issues with accessibility. As JSX offers slightly different syntax to regular HTML, issues with alt text and tabindex, for example, will not be picked up by regular plugins.
@abhu-A-J you can have a look and give your suggestions.
