### ISSUE TITLE
App Promotional Website

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_chennai_website#900]
An website that showcases the features of the app and also the Mockups present.
[https://www.awwwards.com/30-beautiful-app-websites.html](https://www.awwwards.com/30-beautiful-app-websites.html)
I will provide the xd file on slack if required for that

**Comment by aashimgarg** [comment]
@anushbhatia i can work on this!

**Comment by anushbhatia** [comment]
You guys work on React version of site and complete it

**Comment by aashimgarg** [comment]
its almost done!

**Comment by Adyasha8105** [comment]
@anushbhatia Can I work on this?

**Comment by anushbhatia** [comment]
@aashimgarg finish the react version till then @Adyasha8105 can work. If u make a better design then i will merge it?

**Comment by mundane140** [comment]
Do you need help with this one?
