### ISSUE TITLE
Attaching Testimonials of the team!!

### ISSUE THREAD

**Issue by falguniraina** [smaranjitghose/girlscript_chennai_website#932]

**Comment by smaranjitghose** [comment]
@falguniraina Can you please elaborate more on this? And if possible provide a sample design?

**Comment by falguniraina** [comment]
Sure!!I meant that if we could have testimonials from the team members or ratings from the people like these shown below
![Uploading Screenshot from 2020-07-16 15-03-12.png…]()

![Screenshot from 2020-07-16 15-00-59](https://user-images.githubusercontent.com/48027052/87655439-de209600-c775-11ea-8fd7-7467c6d0ed2a.png)

**Comment by falguniraina** [comment]
Sure!!I meant that if we could have the testimonials below the our team section from the customers like shown below
![Screenshot from 2020-07-16 15-03-12](https://user-images.githubusercontent.com/48027052/87657191-1a54f600-c778-11ea-8898-964583b988e9.png)
![Screenshot from 2020-07-16 15-17-00](https://user-images.githubusercontent.com/48027052/87657209-23de5e00-c778-11ea-84f2-75298c79e2d5.png)
![Screenshot from 2020-07-16 15-16-36](https://user-images.githubusercontent.com/48027052/87657244-3193e380-c778-11ea-8ea1-11bcd3673fb7.png)

![Screenshot from 2020-07-16 15-00-59](https://user-images.githubusercontent.com/48027052/87657011-e11c8600-c777-11ea-8e90-cf2c90abfbc9.png)
I got this idea after seeing this on the girlscript website only!

**Comment by falguniraina** [comment]
Sir is there any  active slack channel for this project ??Also I wanted to know how to start this site on my local environment as i wanted to test some changes so could you please help with that??

**Comment by anushbhatia** [comment]
just drop your email id here we will add you to the slack

**Comment by falguniraina** [comment]
email-rainadiv01@gmail.com
Also sir I am a beginner in open source(till now I had only made changes in the documentation so this would be my first ever change in the code part) so please if you could help me with setting this up locally so that i could test the changes i made are effective or not!!

**Comment by smaranjitghose** [comment]
Sure we would love to help you out!

**Comment by falguniraina** [comment]
Thanks!!
please guide me how to get started

**Comment by anushbhatia** [comment]
Sent you the invite 😊

**Comment by falguniraina** [comment]
Sir,I didn't received any invitation mail for the slack channel 😅

**Comment by anushbhatia** [comment]
just check your spam folder

**Comment by falguniraina** [comment]
> just check your spam folder

Already checked sir Its not there

**Comment by anushbhatia** [comment]
https://join.slack.com/t/psoc2020/shared_invite/zt-fiv5t4wh-b7lRK251D1nbJ2UtUlLjlA

**Comment by falguniraina** [comment]
> https://join.slack.com/t/psoc2020/shared_invite/zt-fiv5t4wh-b7lRK251D1nbJ2UtUlLjlA

Thanks a lot!!

**Comment by falguniraina** [comment]
#941
