### ISSUE TITLE
To make Read more button usable

### ISSUE THREAD

**Issue by falguniraina** [smaranjitghose/girlscript_chennai_website#933]
![Screenshot from 2020-07-15 22-39-31](https://user-images.githubusercontent.com/48027052/87574584-31e69d00-c6ec-11ea-9de2-47b732dd1f28.png)
if we select this read more button it should open up a page where we could get the detailed information!!

**Comment by aavishkarmishra** [comment]
I would like to work on this issue, will you provide the detailed content or I should have to write that also.

**Comment by smaranjitghose** [comment]
> I would like to work on this issue, will you provide the detailed content or I should have to write that also.

This project is meant to be boilerplate for all GirlScript Foundation chapters. You can make use of any events related to them instead of using a Lorem Ipsum placeholder text

**Comment by aavishkarmishra** [comment]
Hello @smaranjitghose , will you review the pull request? And tell me how can I request review from someone.

**Comment by kavyashree1903** [comment]
@smaranjitghose can I work on this?

**Comment by smaranjitghose** [comment]
> @smaranjitghose can I work on this?

Sure

**Comment by Maaz-Code** [comment]
can I work on this?

**Comment by Maaz-Code** [comment]
@smaranjitghose can you tell me what kind of info should the read more button open to and from where can I get the info? I am working on this currently.

**Comment by Maaz-Code** [comment]
![1](https://user-images.githubusercontent.com/65590762/107645515-c921cc00-6c9e-11eb-8e8a-2817119380b6.png)
![2](https://user-images.githubusercontent.com/65590762/107645523-caeb8f80-6c9e-11eb-9c18-0f42557371f4.png)

@smaranjitghose If this fine then I will do the PR or else you can suggest any change if you want?
