### ISSUE TITLE
Github And LinkedIn

### ISSUE THREAD

**Issue by Priya19999** [smaranjitghose/girlscript_chennai_website#946]
Description
When we click on the GitHub and LinkedIn logo at the end of the page it is showing error.
Expected Behavior
Girlscript Chennai website has a GitHub page and a  so it should Link us directly to the page

![Screenshot (286)](https://user-images.githubusercontent.com/46641222/90113668-54151e80-dd6f-11ea-8b28-da509e7e5936.png)
![Screenshot (285)](https://user-images.githubusercontent.com/46641222/90113684-57a8a580-dd6f-11ea-89eb-b160d4ef2ea8.png)

**Comment by anushbhatia** [comment]
They don't have the pages for them so we can't add that

**Comment by Priya19999** [comment]
Ok sir, I thought that we can provide the link in the code. I didn't know that the website will create its own different pages for GitHub and linkedIn.

**Comment by anushbhatia** [comment]
yess it should be but they haven't done so we can't

**Comment by Priya19999** [comment]
Okay, Sir, I will close it sorry for the disturbance.
