### ISSUE TITLE
Button is not working properly

### ISSUE THREAD

**Issue by himanshujaidka** [smaranjitghose/girlscript_chennai_website#949]
**Describe the bug**
"Link to Github Repository" button is not working properly, after clicking, it has to show respected 

![AB](https://user-images.githubusercontent.com/58654018/94052576-c0675100-fdf6-11ea-8f73-0b8675223b69.png)

**Comment by himanshujaidka** [comment]
need help in this isuue

**Comment by himanshujaidka** [comment]
is anyone there to help me out?

**Comment by smaranjitghose** [comment]
> is anyone there to help me out?

Your ISSUE Description was unclear as you forgot to delete the template😅
Can you please elaborate on the issue with the GitHub button?

**Comment by himanshujaidka** [comment]
@smaranjitghose pls go to the achievements page and trying to press the link to GitHub  repo button and you will find that button is not working accordingly, so to solve that bug I need help .

**Comment by anushbhatia** [comment]
What help do you need

**Comment by varun14gb** [comment]
I understood the problem.
Link to Github Repository in project card doesn't work.
Can I work on this issue?

**Comment by varun14gb** [comment]
@smaranjitghose I have added a PR #952  regarding this issue

**Comment by neetisaharan** [comment]
may i work on this issue?

**Comment by Maaz-Code** [comment]
I think the issue is resolved.
